// source: account_rpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var treeleaf_pb = require('./treeleaf_pb.js');
goog.object.extend(proto, treeleaf_pb);
var account_pb = require('./account_pb.js');
goog.object.extend(proto, account_pb);
var auth_pb = require('./auth_pb.js');
goog.object.extend(proto, auth_pb);
goog.exportSymbol('proto.brilltech.maaser.rpc.AccountBaseRequest', null, global);
goog.exportSymbol('proto.brilltech.maaser.rpc.AccountBaseResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.rpc.AccountBaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.brilltech.maaser.rpc.AccountBaseRequest.repeatedFields_, null);
};
goog.inherits(proto.brilltech.maaser.rpc.AccountBaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.rpc.AccountBaseRequest.displayName = 'proto.brilltech.maaser.rpc.AccountBaseRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.rpc.AccountBaseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.brilltech.maaser.rpc.AccountBaseResponse.repeatedFields_, null);
};
goog.inherits(proto.brilltech.maaser.rpc.AccountBaseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.rpc.AccountBaseResponse.displayName = 'proto.brilltech.maaser.rpc.AccountBaseResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.rpc.AccountBaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.rpc.AccountBaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    refid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    stringvalue: jspb.Message.getFieldWithDefault(msg, 2, ""),
    stringvaluesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    intvalue: jspb.Message.getFieldWithDefault(msg, 4, 0),
    longvalue: jspb.Message.getFieldWithDefault(msg, 5, 0),
    boolvalue: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    doublevalue: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    userid: jspb.Message.getFieldWithDefault(msg, 8, ""),
    debug: (f = msg.getDebug()) && treeleaf_pb.Debug.toObject(includeInstance, f),
    dataquery: (f = msg.getDataquery()) && treeleaf_pb.DataQuery.toObject(includeInstance, f),
    authorization: (f = msg.getAuthorization()) && auth_pb.Authorization.toObject(includeInstance, f),
    accountverification: (f = msg.getAccountverification()) && account_pb.AccountVerification.toObject(includeInstance, f),
    passwordchangerequest: (f = msg.getPasswordchangerequest()) && account_pb.PasswordChangeRequest.toObject(includeInstance, f),
    passwordreset: (f = msg.getPasswordreset()) && account_pb.PasswordReset.toObject(includeInstance, f),
    user: (f = msg.getUser()) && account_pb.User.toObject(includeInstance, f),
    client: (f = msg.getClient()) && account_pb.Client.toObject(includeInstance, f),
    employee: (f = msg.getEmployee()) && account_pb.Employee.toObject(includeInstance, f),
    account: (f = msg.getAccount()) && account_pb.Account.toObject(includeInstance, f),
    clientfilterrequest: (f = msg.getClientfilterrequest()) && account_pb.ClientFilter.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.rpc.AccountBaseRequest;
  return proto.brilltech.maaser.rpc.AccountBaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.rpc.AccountBaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRefid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringvalue(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addStringvalues(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIntvalue(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLongvalue(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBoolvalue(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDoublevalue(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 9:
      var value = new treeleaf_pb.Debug;
      reader.readMessage(value,treeleaf_pb.Debug.deserializeBinaryFromReader);
      msg.setDebug(value);
      break;
    case 10:
      var value = new treeleaf_pb.DataQuery;
      reader.readMessage(value,treeleaf_pb.DataQuery.deserializeBinaryFromReader);
      msg.setDataquery(value);
      break;
    case 11:
      var value = new auth_pb.Authorization;
      reader.readMessage(value,auth_pb.Authorization.deserializeBinaryFromReader);
      msg.setAuthorization(value);
      break;
    case 12:
      var value = new account_pb.AccountVerification;
      reader.readMessage(value,account_pb.AccountVerification.deserializeBinaryFromReader);
      msg.setAccountverification(value);
      break;
    case 13:
      var value = new account_pb.PasswordChangeRequest;
      reader.readMessage(value,account_pb.PasswordChangeRequest.deserializeBinaryFromReader);
      msg.setPasswordchangerequest(value);
      break;
    case 14:
      var value = new account_pb.PasswordReset;
      reader.readMessage(value,account_pb.PasswordReset.deserializeBinaryFromReader);
      msg.setPasswordreset(value);
      break;
    case 15:
      var value = new account_pb.User;
      reader.readMessage(value,account_pb.User.deserializeBinaryFromReader);
      msg.setUser(value);
      break;
    case 16:
      var value = new account_pb.Client;
      reader.readMessage(value,account_pb.Client.deserializeBinaryFromReader);
      msg.setClient(value);
      break;
    case 17:
      var value = new account_pb.Employee;
      reader.readMessage(value,account_pb.Employee.deserializeBinaryFromReader);
      msg.setEmployee(value);
      break;
    case 18:
      var value = new account_pb.Account;
      reader.readMessage(value,account_pb.Account.deserializeBinaryFromReader);
      msg.setAccount(value);
      break;
    case 19:
      var value = new account_pb.ClientFilter;
      reader.readMessage(value,account_pb.ClientFilter.deserializeBinaryFromReader);
      msg.setClientfilterrequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.rpc.AccountBaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.rpc.AccountBaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRefid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStringvalue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStringvaluesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getIntvalue();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getLongvalue();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getBoolvalue();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getDoublevalue();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getDebug();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      treeleaf_pb.Debug.serializeBinaryToWriter
    );
  }
  f = message.getDataquery();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      treeleaf_pb.DataQuery.serializeBinaryToWriter
    );
  }
  f = message.getAuthorization();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      auth_pb.Authorization.serializeBinaryToWriter
    );
  }
  f = message.getAccountverification();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      account_pb.AccountVerification.serializeBinaryToWriter
    );
  }
  f = message.getPasswordchangerequest();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      account_pb.PasswordChangeRequest.serializeBinaryToWriter
    );
  }
  f = message.getPasswordreset();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      account_pb.PasswordReset.serializeBinaryToWriter
    );
  }
  f = message.getUser();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      account_pb.User.serializeBinaryToWriter
    );
  }
  f = message.getClient();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      account_pb.Client.serializeBinaryToWriter
    );
  }
  f = message.getEmployee();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      account_pb.Employee.serializeBinaryToWriter
    );
  }
  f = message.getAccount();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      account_pb.Account.serializeBinaryToWriter
    );
  }
  f = message.getClientfilterrequest();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      account_pb.ClientFilter.serializeBinaryToWriter
    );
  }
};


/**
 * optional string refId = 1;
 * @return {string}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getRefid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setRefid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string stringValue = 2;
 * @return {string}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getStringvalue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setStringvalue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string stringValues = 3;
 * @return {!Array<string>}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getStringvaluesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setStringvaluesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.addStringvalues = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.clearStringvaluesList = function() {
  return this.setStringvaluesList([]);
};


/**
 * optional int32 intValue = 4;
 * @return {number}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getIntvalue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setIntvalue = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 longValue = 5;
 * @return {number}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getLongvalue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setLongvalue = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional bool boolValue = 6;
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getBoolvalue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setBoolvalue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool doubleValue = 7;
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getDoublevalue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setDoublevalue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional string userId = 8;
 * @return {string}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional treeleaf.protos.Debug debug = 9;
 * @return {?proto.treeleaf.protos.Debug}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getDebug = function() {
  return /** @type{?proto.treeleaf.protos.Debug} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.Debug, 9));
};


/**
 * @param {?proto.treeleaf.protos.Debug|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setDebug = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.clearDebug = function() {
  return this.setDebug(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.hasDebug = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional treeleaf.protos.DataQuery dataQuery = 10;
 * @return {?proto.treeleaf.protos.DataQuery}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getDataquery = function() {
  return /** @type{?proto.treeleaf.protos.DataQuery} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.DataQuery, 10));
};


/**
 * @param {?proto.treeleaf.protos.DataQuery|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setDataquery = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.clearDataquery = function() {
  return this.setDataquery(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.hasDataquery = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional brilltech.maaser.entities.Authorization authorization = 11;
 * @return {?proto.brilltech.maaser.entities.Authorization}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getAuthorization = function() {
  return /** @type{?proto.brilltech.maaser.entities.Authorization} */ (
    jspb.Message.getWrapperField(this, auth_pb.Authorization, 11));
};


/**
 * @param {?proto.brilltech.maaser.entities.Authorization|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setAuthorization = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.clearAuthorization = function() {
  return this.setAuthorization(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.hasAuthorization = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional brilltech.maaser.entities.AccountVerification accountVerification = 12;
 * @return {?proto.brilltech.maaser.entities.AccountVerification}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getAccountverification = function() {
  return /** @type{?proto.brilltech.maaser.entities.AccountVerification} */ (
    jspb.Message.getWrapperField(this, account_pb.AccountVerification, 12));
};


/**
 * @param {?proto.brilltech.maaser.entities.AccountVerification|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setAccountverification = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.clearAccountverification = function() {
  return this.setAccountverification(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.hasAccountverification = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional brilltech.maaser.entities.PasswordChangeRequest passwordChangeRequest = 13;
 * @return {?proto.brilltech.maaser.entities.PasswordChangeRequest}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getPasswordchangerequest = function() {
  return /** @type{?proto.brilltech.maaser.entities.PasswordChangeRequest} */ (
    jspb.Message.getWrapperField(this, account_pb.PasswordChangeRequest, 13));
};


/**
 * @param {?proto.brilltech.maaser.entities.PasswordChangeRequest|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setPasswordchangerequest = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.clearPasswordchangerequest = function() {
  return this.setPasswordchangerequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.hasPasswordchangerequest = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional brilltech.maaser.entities.PasswordReset passwordReset = 14;
 * @return {?proto.brilltech.maaser.entities.PasswordReset}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getPasswordreset = function() {
  return /** @type{?proto.brilltech.maaser.entities.PasswordReset} */ (
    jspb.Message.getWrapperField(this, account_pb.PasswordReset, 14));
};


/**
 * @param {?proto.brilltech.maaser.entities.PasswordReset|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setPasswordreset = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.clearPasswordreset = function() {
  return this.setPasswordreset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.hasPasswordreset = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional brilltech.maaser.entities.User user = 15;
 * @return {?proto.brilltech.maaser.entities.User}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getUser = function() {
  return /** @type{?proto.brilltech.maaser.entities.User} */ (
    jspb.Message.getWrapperField(this, account_pb.User, 15));
};


/**
 * @param {?proto.brilltech.maaser.entities.User|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setUser = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.clearUser = function() {
  return this.setUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.hasUser = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional brilltech.maaser.entities.Client client = 16;
 * @return {?proto.brilltech.maaser.entities.Client}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getClient = function() {
  return /** @type{?proto.brilltech.maaser.entities.Client} */ (
    jspb.Message.getWrapperField(this, account_pb.Client, 16));
};


/**
 * @param {?proto.brilltech.maaser.entities.Client|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setClient = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.clearClient = function() {
  return this.setClient(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.hasClient = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional brilltech.maaser.entities.Employee employee = 17;
 * @return {?proto.brilltech.maaser.entities.Employee}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getEmployee = function() {
  return /** @type{?proto.brilltech.maaser.entities.Employee} */ (
    jspb.Message.getWrapperField(this, account_pb.Employee, 17));
};


/**
 * @param {?proto.brilltech.maaser.entities.Employee|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setEmployee = function(value) {
  return jspb.Message.setWrapperField(this, 17, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.clearEmployee = function() {
  return this.setEmployee(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.hasEmployee = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional brilltech.maaser.entities.Account account = 18;
 * @return {?proto.brilltech.maaser.entities.Account}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getAccount = function() {
  return /** @type{?proto.brilltech.maaser.entities.Account} */ (
    jspb.Message.getWrapperField(this, account_pb.Account, 18));
};


/**
 * @param {?proto.brilltech.maaser.entities.Account|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setAccount = function(value) {
  return jspb.Message.setWrapperField(this, 18, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.clearAccount = function() {
  return this.setAccount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.hasAccount = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional brilltech.maaser.entities.ClientFilter clientFilterRequest = 19;
 * @return {?proto.brilltech.maaser.entities.ClientFilter}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.getClientfilterrequest = function() {
  return /** @type{?proto.brilltech.maaser.entities.ClientFilter} */ (
    jspb.Message.getWrapperField(this, account_pb.ClientFilter, 19));
};


/**
 * @param {?proto.brilltech.maaser.entities.ClientFilter|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.setClientfilterrequest = function(value) {
  return jspb.Message.setWrapperField(this, 19, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.clearClientfilterrequest = function() {
  return this.setClientfilterrequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseRequest.prototype.hasClientfilterrequest = function() {
  return jspb.Message.getField(this, 19) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.repeatedFields_ = [10,12,14];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.rpc.AccountBaseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.rpc.AccountBaseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    error: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    msg: jspb.Message.getFieldWithDefault(msg, 2, ""),
    errorcode: jspb.Message.getFieldWithDefault(msg, 3, 0),
    success: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    timestamp: jspb.Message.getFieldWithDefault(msg, 5, 0),
    debug: (f = msg.getDebug()) && treeleaf_pb.Debug.toObject(includeInstance, f),
    refid: jspb.Message.getFieldWithDefault(msg, 7, ""),
    loginaccount: (f = msg.getLoginaccount()) && account_pb.LoginAccount.toObject(includeInstance, f),
    user: (f = msg.getUser()) && account_pb.User.toObject(includeInstance, f),
    usersList: jspb.Message.toObjectList(msg.getUsersList(),
    account_pb.User.toObject, includeInstance),
    client: (f = msg.getClient()) && account_pb.Client.toObject(includeInstance, f),
    clientsList: jspb.Message.toObjectList(msg.getClientsList(),
    account_pb.Client.toObject, includeInstance),
    employee: (f = msg.getEmployee()) && account_pb.Employee.toObject(includeInstance, f),
    employeesList: jspb.Message.toObjectList(msg.getEmployeesList(),
    account_pb.Employee.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.rpc.AccountBaseResponse;
  return proto.brilltech.maaser.rpc.AccountBaseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.rpc.AccountBaseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setError(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsg(value);
      break;
    case 3:
      var value = /** @type {!proto.treeleaf.protos.ErrorCode} */ (reader.readEnum());
      msg.setErrorcode(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 6:
      var value = new treeleaf_pb.Debug;
      reader.readMessage(value,treeleaf_pb.Debug.deserializeBinaryFromReader);
      msg.setDebug(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setRefid(value);
      break;
    case 8:
      var value = new account_pb.LoginAccount;
      reader.readMessage(value,account_pb.LoginAccount.deserializeBinaryFromReader);
      msg.setLoginaccount(value);
      break;
    case 9:
      var value = new account_pb.User;
      reader.readMessage(value,account_pb.User.deserializeBinaryFromReader);
      msg.setUser(value);
      break;
    case 10:
      var value = new account_pb.User;
      reader.readMessage(value,account_pb.User.deserializeBinaryFromReader);
      msg.addUsers(value);
      break;
    case 11:
      var value = new account_pb.Client;
      reader.readMessage(value,account_pb.Client.deserializeBinaryFromReader);
      msg.setClient(value);
      break;
    case 12:
      var value = new account_pb.Client;
      reader.readMessage(value,account_pb.Client.deserializeBinaryFromReader);
      msg.addClients(value);
      break;
    case 13:
      var value = new account_pb.Employee;
      reader.readMessage(value,account_pb.Employee.deserializeBinaryFromReader);
      msg.setEmployee(value);
      break;
    case 14:
      var value = new account_pb.Employee;
      reader.readMessage(value,account_pb.Employee.deserializeBinaryFromReader);
      msg.addEmployees(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.rpc.AccountBaseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.rpc.AccountBaseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getError();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMsg();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getErrorcode();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getDebug();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      treeleaf_pb.Debug.serializeBinaryToWriter
    );
  }
  f = message.getRefid();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getLoginaccount();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      account_pb.LoginAccount.serializeBinaryToWriter
    );
  }
  f = message.getUser();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      account_pb.User.serializeBinaryToWriter
    );
  }
  f = message.getUsersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      account_pb.User.serializeBinaryToWriter
    );
  }
  f = message.getClient();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      account_pb.Client.serializeBinaryToWriter
    );
  }
  f = message.getClientsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      account_pb.Client.serializeBinaryToWriter
    );
  }
  f = message.getEmployee();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      account_pb.Employee.serializeBinaryToWriter
    );
  }
  f = message.getEmployeesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      14,
      f,
      account_pb.Employee.serializeBinaryToWriter
    );
  }
};


/**
 * optional bool error = 1;
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.getError = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.setError = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string msg = 2;
 * @return {string}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.getMsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.setMsg = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional treeleaf.protos.ErrorCode errorCode = 3;
 * @return {!proto.treeleaf.protos.ErrorCode}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.getErrorcode = function() {
  return /** @type {!proto.treeleaf.protos.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.treeleaf.protos.ErrorCode} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.setErrorcode = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional bool success = 4;
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional int64 timestamp = 5;
 * @return {number}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional treeleaf.protos.Debug debug = 6;
 * @return {?proto.treeleaf.protos.Debug}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.getDebug = function() {
  return /** @type{?proto.treeleaf.protos.Debug} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.Debug, 6));
};


/**
 * @param {?proto.treeleaf.protos.Debug|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.setDebug = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.clearDebug = function() {
  return this.setDebug(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.hasDebug = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string refId = 7;
 * @return {string}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.getRefid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.setRefid = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional brilltech.maaser.entities.LoginAccount loginAccount = 8;
 * @return {?proto.brilltech.maaser.entities.LoginAccount}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.getLoginaccount = function() {
  return /** @type{?proto.brilltech.maaser.entities.LoginAccount} */ (
    jspb.Message.getWrapperField(this, account_pb.LoginAccount, 8));
};


/**
 * @param {?proto.brilltech.maaser.entities.LoginAccount|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.setLoginaccount = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.clearLoginaccount = function() {
  return this.setLoginaccount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.hasLoginaccount = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional brilltech.maaser.entities.User user = 9;
 * @return {?proto.brilltech.maaser.entities.User}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.getUser = function() {
  return /** @type{?proto.brilltech.maaser.entities.User} */ (
    jspb.Message.getWrapperField(this, account_pb.User, 9));
};


/**
 * @param {?proto.brilltech.maaser.entities.User|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.setUser = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.clearUser = function() {
  return this.setUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.hasUser = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * repeated brilltech.maaser.entities.User users = 10;
 * @return {!Array<!proto.brilltech.maaser.entities.User>}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.getUsersList = function() {
  return /** @type{!Array<!proto.brilltech.maaser.entities.User>} */ (
    jspb.Message.getRepeatedWrapperField(this, account_pb.User, 10));
};


/**
 * @param {!Array<!proto.brilltech.maaser.entities.User>} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.setUsersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.brilltech.maaser.entities.User=} opt_value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.User}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.addUsers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.brilltech.maaser.entities.User, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.clearUsersList = function() {
  return this.setUsersList([]);
};


/**
 * optional brilltech.maaser.entities.Client client = 11;
 * @return {?proto.brilltech.maaser.entities.Client}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.getClient = function() {
  return /** @type{?proto.brilltech.maaser.entities.Client} */ (
    jspb.Message.getWrapperField(this, account_pb.Client, 11));
};


/**
 * @param {?proto.brilltech.maaser.entities.Client|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.setClient = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.clearClient = function() {
  return this.setClient(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.hasClient = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * repeated brilltech.maaser.entities.Client clients = 12;
 * @return {!Array<!proto.brilltech.maaser.entities.Client>}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.getClientsList = function() {
  return /** @type{!Array<!proto.brilltech.maaser.entities.Client>} */ (
    jspb.Message.getRepeatedWrapperField(this, account_pb.Client, 12));
};


/**
 * @param {!Array<!proto.brilltech.maaser.entities.Client>} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.setClientsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.brilltech.maaser.entities.Client=} opt_value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.Client}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.addClients = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.brilltech.maaser.entities.Client, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.clearClientsList = function() {
  return this.setClientsList([]);
};


/**
 * optional brilltech.maaser.entities.Employee employee = 13;
 * @return {?proto.brilltech.maaser.entities.Employee}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.getEmployee = function() {
  return /** @type{?proto.brilltech.maaser.entities.Employee} */ (
    jspb.Message.getWrapperField(this, account_pb.Employee, 13));
};


/**
 * @param {?proto.brilltech.maaser.entities.Employee|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.setEmployee = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.clearEmployee = function() {
  return this.setEmployee(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.hasEmployee = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * repeated brilltech.maaser.entities.Employee employees = 14;
 * @return {!Array<!proto.brilltech.maaser.entities.Employee>}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.getEmployeesList = function() {
  return /** @type{!Array<!proto.brilltech.maaser.entities.Employee>} */ (
    jspb.Message.getRepeatedWrapperField(this, account_pb.Employee, 14));
};


/**
 * @param {!Array<!proto.brilltech.maaser.entities.Employee>} value
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.setEmployeesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 14, value);
};


/**
 * @param {!proto.brilltech.maaser.entities.Employee=} opt_value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.Employee}
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.addEmployees = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 14, opt_value, proto.brilltech.maaser.entities.Employee, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.rpc.AccountBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AccountBaseResponse.prototype.clearEmployeesList = function() {
  return this.setEmployeesList([]);
};


goog.object.extend(exports, proto.brilltech.maaser.rpc);
