// source: ach_rpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var treeleaf_pb = require('./treeleaf_pb.js');
goog.object.extend(proto, treeleaf_pb);
var ach_pb = require('./ach_pb.js');
goog.object.extend(proto, ach_pb);
goog.exportSymbol('proto.brilltech.maaser.rpc.AchBaseRequest', null, global);
goog.exportSymbol('proto.brilltech.maaser.rpc.AchBaseResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.rpc.AchBaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.brilltech.maaser.rpc.AchBaseRequest.repeatedFields_, null);
};
goog.inherits(proto.brilltech.maaser.rpc.AchBaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.rpc.AchBaseRequest.displayName = 'proto.brilltech.maaser.rpc.AchBaseRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.rpc.AchBaseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.brilltech.maaser.rpc.AchBaseResponse.repeatedFields_, null);
};
goog.inherits(proto.brilltech.maaser.rpc.AchBaseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.rpc.AchBaseResponse.displayName = 'proto.brilltech.maaser.rpc.AchBaseResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.brilltech.maaser.rpc.AchBaseRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.rpc.AchBaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.rpc.AchBaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.rpc.AchBaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    refid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    stringvalue: jspb.Message.getFieldWithDefault(msg, 2, ""),
    stringvaluesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    intvalue: jspb.Message.getFieldWithDefault(msg, 4, 0),
    longvalue: jspb.Message.getFieldWithDefault(msg, 5, 0),
    boolvalue: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    doublevalue: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    debug: (f = msg.getDebug()) && treeleaf_pb.Debug.toObject(includeInstance, f),
    achdata: (f = msg.getAchdata()) && ach_pb.AchData.toObject(includeInstance, f),
    fileheaderrecord: (f = msg.getFileheaderrecord()) && ach_pb.FileHeaderRecord.toObject(includeInstance, f),
    batchheaderrecord: (f = msg.getBatchheaderrecord()) && ach_pb.BatchHeaderRecord.toObject(includeInstance, f),
    ppdentrydetailrecord: (f = msg.getPpdentrydetailrecord()) && ach_pb.PPDEntryDetailRecord.toObject(includeInstance, f),
    batchcontrolrecord: (f = msg.getBatchcontrolrecord()) && ach_pb.BatchControlRecord.toObject(includeInstance, f),
    filecontrolrecord: (f = msg.getFilecontrolrecord()) && ach_pb.FileControlRecord.toObject(includeInstance, f),
    filereturnedrecord: (f = msg.getFilereturnedrecord()) && ach_pb.FileReturnRecord.toObject(includeInstance, f),
    achlog: (f = msg.getAchlog()) && ach_pb.AchLog.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.rpc.AchBaseRequest;
  return proto.brilltech.maaser.rpc.AchBaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.rpc.AchBaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRefid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringvalue(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addStringvalues(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIntvalue(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLongvalue(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBoolvalue(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDoublevalue(value);
      break;
    case 8:
      var value = new treeleaf_pb.Debug;
      reader.readMessage(value,treeleaf_pb.Debug.deserializeBinaryFromReader);
      msg.setDebug(value);
      break;
    case 9:
      var value = new ach_pb.AchData;
      reader.readMessage(value,ach_pb.AchData.deserializeBinaryFromReader);
      msg.setAchdata(value);
      break;
    case 10:
      var value = new ach_pb.FileHeaderRecord;
      reader.readMessage(value,ach_pb.FileHeaderRecord.deserializeBinaryFromReader);
      msg.setFileheaderrecord(value);
      break;
    case 11:
      var value = new ach_pb.BatchHeaderRecord;
      reader.readMessage(value,ach_pb.BatchHeaderRecord.deserializeBinaryFromReader);
      msg.setBatchheaderrecord(value);
      break;
    case 12:
      var value = new ach_pb.PPDEntryDetailRecord;
      reader.readMessage(value,ach_pb.PPDEntryDetailRecord.deserializeBinaryFromReader);
      msg.setPpdentrydetailrecord(value);
      break;
    case 13:
      var value = new ach_pb.BatchControlRecord;
      reader.readMessage(value,ach_pb.BatchControlRecord.deserializeBinaryFromReader);
      msg.setBatchcontrolrecord(value);
      break;
    case 14:
      var value = new ach_pb.FileControlRecord;
      reader.readMessage(value,ach_pb.FileControlRecord.deserializeBinaryFromReader);
      msg.setFilecontrolrecord(value);
      break;
    case 15:
      var value = new ach_pb.FileReturnRecord;
      reader.readMessage(value,ach_pb.FileReturnRecord.deserializeBinaryFromReader);
      msg.setFilereturnedrecord(value);
      break;
    case 16:
      var value = new ach_pb.AchLog;
      reader.readMessage(value,ach_pb.AchLog.deserializeBinaryFromReader);
      msg.setAchlog(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.rpc.AchBaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.rpc.AchBaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.rpc.AchBaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRefid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStringvalue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStringvaluesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getIntvalue();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getLongvalue();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getBoolvalue();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getDoublevalue();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getDebug();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      treeleaf_pb.Debug.serializeBinaryToWriter
    );
  }
  f = message.getAchdata();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      ach_pb.AchData.serializeBinaryToWriter
    );
  }
  f = message.getFileheaderrecord();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      ach_pb.FileHeaderRecord.serializeBinaryToWriter
    );
  }
  f = message.getBatchheaderrecord();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      ach_pb.BatchHeaderRecord.serializeBinaryToWriter
    );
  }
  f = message.getPpdentrydetailrecord();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      ach_pb.PPDEntryDetailRecord.serializeBinaryToWriter
    );
  }
  f = message.getBatchcontrolrecord();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      ach_pb.BatchControlRecord.serializeBinaryToWriter
    );
  }
  f = message.getFilecontrolrecord();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      ach_pb.FileControlRecord.serializeBinaryToWriter
    );
  }
  f = message.getFilereturnedrecord();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      ach_pb.FileReturnRecord.serializeBinaryToWriter
    );
  }
  f = message.getAchlog();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      ach_pb.AchLog.serializeBinaryToWriter
    );
  }
};


/**
 * optional string refId = 1;
 * @return {string}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.getRefid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.setRefid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string stringValue = 2;
 * @return {string}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.getStringvalue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.setStringvalue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string stringValues = 3;
 * @return {!Array<string>}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.getStringvaluesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.setStringvaluesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.addStringvalues = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.clearStringvaluesList = function() {
  return this.setStringvaluesList([]);
};


/**
 * optional int32 intValue = 4;
 * @return {number}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.getIntvalue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.setIntvalue = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 longValue = 5;
 * @return {number}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.getLongvalue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.setLongvalue = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional bool boolValue = 6;
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.getBoolvalue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.setBoolvalue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool doubleValue = 7;
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.getDoublevalue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.setDoublevalue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional treeleaf.protos.Debug debug = 8;
 * @return {?proto.treeleaf.protos.Debug}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.getDebug = function() {
  return /** @type{?proto.treeleaf.protos.Debug} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.Debug, 8));
};


/**
 * @param {?proto.treeleaf.protos.Debug|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.setDebug = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.clearDebug = function() {
  return this.setDebug(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.hasDebug = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional brilltech.maaser.entities.AchData achData = 9;
 * @return {?proto.brilltech.maaser.entities.AchData}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.getAchdata = function() {
  return /** @type{?proto.brilltech.maaser.entities.AchData} */ (
    jspb.Message.getWrapperField(this, ach_pb.AchData, 9));
};


/**
 * @param {?proto.brilltech.maaser.entities.AchData|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.setAchdata = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.clearAchdata = function() {
  return this.setAchdata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.hasAchdata = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional brilltech.maaser.entities.FileHeaderRecord fileHeaderRecord = 10;
 * @return {?proto.brilltech.maaser.entities.FileHeaderRecord}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.getFileheaderrecord = function() {
  return /** @type{?proto.brilltech.maaser.entities.FileHeaderRecord} */ (
    jspb.Message.getWrapperField(this, ach_pb.FileHeaderRecord, 10));
};


/**
 * @param {?proto.brilltech.maaser.entities.FileHeaderRecord|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.setFileheaderrecord = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.clearFileheaderrecord = function() {
  return this.setFileheaderrecord(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.hasFileheaderrecord = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional brilltech.maaser.entities.BatchHeaderRecord batchHeaderRecord = 11;
 * @return {?proto.brilltech.maaser.entities.BatchHeaderRecord}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.getBatchheaderrecord = function() {
  return /** @type{?proto.brilltech.maaser.entities.BatchHeaderRecord} */ (
    jspb.Message.getWrapperField(this, ach_pb.BatchHeaderRecord, 11));
};


/**
 * @param {?proto.brilltech.maaser.entities.BatchHeaderRecord|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.setBatchheaderrecord = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.clearBatchheaderrecord = function() {
  return this.setBatchheaderrecord(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.hasBatchheaderrecord = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional brilltech.maaser.entities.PPDEntryDetailRecord ppdEntryDetailRecord = 12;
 * @return {?proto.brilltech.maaser.entities.PPDEntryDetailRecord}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.getPpdentrydetailrecord = function() {
  return /** @type{?proto.brilltech.maaser.entities.PPDEntryDetailRecord} */ (
    jspb.Message.getWrapperField(this, ach_pb.PPDEntryDetailRecord, 12));
};


/**
 * @param {?proto.brilltech.maaser.entities.PPDEntryDetailRecord|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.setPpdentrydetailrecord = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.clearPpdentrydetailrecord = function() {
  return this.setPpdentrydetailrecord(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.hasPpdentrydetailrecord = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional brilltech.maaser.entities.BatchControlRecord batchControlRecord = 13;
 * @return {?proto.brilltech.maaser.entities.BatchControlRecord}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.getBatchcontrolrecord = function() {
  return /** @type{?proto.brilltech.maaser.entities.BatchControlRecord} */ (
    jspb.Message.getWrapperField(this, ach_pb.BatchControlRecord, 13));
};


/**
 * @param {?proto.brilltech.maaser.entities.BatchControlRecord|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.setBatchcontrolrecord = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.clearBatchcontrolrecord = function() {
  return this.setBatchcontrolrecord(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.hasBatchcontrolrecord = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional brilltech.maaser.entities.FileControlRecord fileControlRecord = 14;
 * @return {?proto.brilltech.maaser.entities.FileControlRecord}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.getFilecontrolrecord = function() {
  return /** @type{?proto.brilltech.maaser.entities.FileControlRecord} */ (
    jspb.Message.getWrapperField(this, ach_pb.FileControlRecord, 14));
};


/**
 * @param {?proto.brilltech.maaser.entities.FileControlRecord|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.setFilecontrolrecord = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.clearFilecontrolrecord = function() {
  return this.setFilecontrolrecord(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.hasFilecontrolrecord = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional brilltech.maaser.entities.FileReturnRecord fileReturnedRecord = 15;
 * @return {?proto.brilltech.maaser.entities.FileReturnRecord}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.getFilereturnedrecord = function() {
  return /** @type{?proto.brilltech.maaser.entities.FileReturnRecord} */ (
    jspb.Message.getWrapperField(this, ach_pb.FileReturnRecord, 15));
};


/**
 * @param {?proto.brilltech.maaser.entities.FileReturnRecord|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.setFilereturnedrecord = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.clearFilereturnedrecord = function() {
  return this.setFilereturnedrecord(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.hasFilereturnedrecord = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional brilltech.maaser.entities.AchLog achLog = 16;
 * @return {?proto.brilltech.maaser.entities.AchLog}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.getAchlog = function() {
  return /** @type{?proto.brilltech.maaser.entities.AchLog} */ (
    jspb.Message.getWrapperField(this, ach_pb.AchLog, 16));
};


/**
 * @param {?proto.brilltech.maaser.entities.AchLog|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.setAchlog = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AchBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.clearAchlog = function() {
  return this.setAchlog(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AchBaseRequest.prototype.hasAchlog = function() {
  return jspb.Message.getField(this, 16) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.brilltech.maaser.rpc.AchBaseResponse.repeatedFields_ = [7,9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.rpc.AchBaseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.rpc.AchBaseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.rpc.AchBaseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    error: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    msg: jspb.Message.getFieldWithDefault(msg, 2, ""),
    errorcode: jspb.Message.getFieldWithDefault(msg, 3, 0),
    success: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    debug: (f = msg.getDebug()) && treeleaf_pb.Debug.toObject(includeInstance, f),
    achdata: (f = msg.getAchdata()) && ach_pb.AchData.toObject(includeInstance, f),
    achdatalistList: jspb.Message.toObjectList(msg.getAchdatalistList(),
    ach_pb.AchData.toObject, includeInstance),
    achlog: (f = msg.getAchlog()) && ach_pb.AchLog.toObject(includeInstance, f),
    achlogsList: jspb.Message.toObjectList(msg.getAchlogsList(),
    ach_pb.AchLog.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.rpc.AchBaseResponse}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.rpc.AchBaseResponse;
  return proto.brilltech.maaser.rpc.AchBaseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.rpc.AchBaseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.rpc.AchBaseResponse}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setError(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsg(value);
      break;
    case 3:
      var value = /** @type {!proto.treeleaf.protos.ErrorCode} */ (reader.readEnum());
      msg.setErrorcode(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 5:
      var value = new treeleaf_pb.Debug;
      reader.readMessage(value,treeleaf_pb.Debug.deserializeBinaryFromReader);
      msg.setDebug(value);
      break;
    case 6:
      var value = new ach_pb.AchData;
      reader.readMessage(value,ach_pb.AchData.deserializeBinaryFromReader);
      msg.setAchdata(value);
      break;
    case 7:
      var value = new ach_pb.AchData;
      reader.readMessage(value,ach_pb.AchData.deserializeBinaryFromReader);
      msg.addAchdatalist(value);
      break;
    case 8:
      var value = new ach_pb.AchLog;
      reader.readMessage(value,ach_pb.AchLog.deserializeBinaryFromReader);
      msg.setAchlog(value);
      break;
    case 9:
      var value = new ach_pb.AchLog;
      reader.readMessage(value,ach_pb.AchLog.deserializeBinaryFromReader);
      msg.addAchlogs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.rpc.AchBaseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.rpc.AchBaseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.rpc.AchBaseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getError();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMsg();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getErrorcode();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getDebug();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      treeleaf_pb.Debug.serializeBinaryToWriter
    );
  }
  f = message.getAchdata();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      ach_pb.AchData.serializeBinaryToWriter
    );
  }
  f = message.getAchdatalistList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      ach_pb.AchData.serializeBinaryToWriter
    );
  }
  f = message.getAchlog();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      ach_pb.AchLog.serializeBinaryToWriter
    );
  }
  f = message.getAchlogsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      ach_pb.AchLog.serializeBinaryToWriter
    );
  }
};


/**
 * optional bool error = 1;
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.getError = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.setError = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string msg = 2;
 * @return {string}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.getMsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.setMsg = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional treeleaf.protos.ErrorCode errorCode = 3;
 * @return {!proto.treeleaf.protos.ErrorCode}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.getErrorcode = function() {
  return /** @type {!proto.treeleaf.protos.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.treeleaf.protos.ErrorCode} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.setErrorcode = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional bool success = 4;
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional treeleaf.protos.Debug debug = 5;
 * @return {?proto.treeleaf.protos.Debug}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.getDebug = function() {
  return /** @type{?proto.treeleaf.protos.Debug} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.Debug, 5));
};


/**
 * @param {?proto.treeleaf.protos.Debug|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.setDebug = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AchBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.clearDebug = function() {
  return this.setDebug(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.hasDebug = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional brilltech.maaser.entities.AchData achData = 6;
 * @return {?proto.brilltech.maaser.entities.AchData}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.getAchdata = function() {
  return /** @type{?proto.brilltech.maaser.entities.AchData} */ (
    jspb.Message.getWrapperField(this, ach_pb.AchData, 6));
};


/**
 * @param {?proto.brilltech.maaser.entities.AchData|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.setAchdata = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AchBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.clearAchdata = function() {
  return this.setAchdata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.hasAchdata = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated brilltech.maaser.entities.AchData achDataList = 7;
 * @return {!Array<!proto.brilltech.maaser.entities.AchData>}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.getAchdatalistList = function() {
  return /** @type{!Array<!proto.brilltech.maaser.entities.AchData>} */ (
    jspb.Message.getRepeatedWrapperField(this, ach_pb.AchData, 7));
};


/**
 * @param {!Array<!proto.brilltech.maaser.entities.AchData>} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.setAchdatalistList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.brilltech.maaser.entities.AchData=} opt_value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.AchData}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.addAchdatalist = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.brilltech.maaser.entities.AchData, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.rpc.AchBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.clearAchdatalistList = function() {
  return this.setAchdatalistList([]);
};


/**
 * optional brilltech.maaser.entities.AchLog achLog = 8;
 * @return {?proto.brilltech.maaser.entities.AchLog}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.getAchlog = function() {
  return /** @type{?proto.brilltech.maaser.entities.AchLog} */ (
    jspb.Message.getWrapperField(this, ach_pb.AchLog, 8));
};


/**
 * @param {?proto.brilltech.maaser.entities.AchLog|undefined} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.setAchlog = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.AchBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.clearAchlog = function() {
  return this.setAchlog(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.hasAchlog = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * repeated brilltech.maaser.entities.AchLog achLogs = 9;
 * @return {!Array<!proto.brilltech.maaser.entities.AchLog>}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.getAchlogsList = function() {
  return /** @type{!Array<!proto.brilltech.maaser.entities.AchLog>} */ (
    jspb.Message.getRepeatedWrapperField(this, ach_pb.AchLog, 9));
};


/**
 * @param {!Array<!proto.brilltech.maaser.entities.AchLog>} value
 * @return {!proto.brilltech.maaser.rpc.AchBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.setAchlogsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.brilltech.maaser.entities.AchLog=} opt_value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.AchLog}
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.addAchlogs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.brilltech.maaser.entities.AchLog, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.rpc.AchBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.AchBaseResponse.prototype.clearAchlogsList = function() {
  return this.setAchlogsList([]);
};


goog.object.extend(exports, proto.brilltech.maaser.rpc);
