// source: auth.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var treeleaf_pb = require('./treeleaf_pb.js');
goog.object.extend(proto, treeleaf_pb);
var maaser_pb = require('./maaser_pb.js');
goog.object.extend(proto, maaser_pb);
var account_pb = require('./account_pb.js');
goog.object.extend(proto, account_pb);
var permission_pb = require('./permission_pb.js');
goog.object.extend(proto, permission_pb);
goog.exportSymbol('proto.brilltech.maaser.entities.AuthResponse', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.Authorization', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.Jwt', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.JwtLit', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.LoginRequest', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.LoginResponse', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.Session', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.Session = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.brilltech.maaser.entities.Session.repeatedFields_, null);
};
goog.inherits(proto.brilltech.maaser.entities.Session, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.entities.Session.displayName = 'proto.brilltech.maaser.entities.Session';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.LoginRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.brilltech.maaser.entities.LoginRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.entities.LoginRequest.displayName = 'proto.brilltech.maaser.entities.LoginRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.Authorization = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.brilltech.maaser.entities.Authorization, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.entities.Authorization.displayName = 'proto.brilltech.maaser.entities.Authorization';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.AuthResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.brilltech.maaser.entities.AuthResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.entities.AuthResponse.displayName = 'proto.brilltech.maaser.entities.AuthResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.LoginResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.brilltech.maaser.entities.LoginResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.entities.LoginResponse.displayName = 'proto.brilltech.maaser.entities.LoginResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.Jwt = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.brilltech.maaser.entities.Jwt, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.entities.Jwt.displayName = 'proto.brilltech.maaser.entities.Jwt';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.JwtLit = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.brilltech.maaser.entities.JwtLit.repeatedFields_, null);
};
goog.inherits(proto.brilltech.maaser.entities.JwtLit, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.entities.JwtLit.displayName = 'proto.brilltech.maaser.entities.JwtLit';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.brilltech.maaser.entities.Session.repeatedFields_ = [12];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.Session.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.Session.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.Session} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.Session.toObject = function(includeInstance, msg) {
  var f, obj = {
    sessionid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    accountid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    clientdetail: (f = msg.getClientdetail()) && treeleaf_pb.ClientDetail.toObject(includeInstance, f),
    timestamp: jspb.Message.getFieldWithDefault(msg, 4, 0),
    active: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    pushtoken: jspb.Message.getFieldWithDefault(msg, 6, ""),
    accounttype: jspb.Message.getFieldWithDefault(msg, 7, 0),
    loginid: jspb.Message.getFieldWithDefault(msg, 8, ""),
    user: (f = msg.getUser()) && account_pb.User.toObject(includeInstance, f),
    client: (f = msg.getClient()) && account_pb.Client.toObject(includeInstance, f),
    employee: (f = msg.getEmployee()) && account_pb.Employee.toObject(includeInstance, f),
    permissionsList: jspb.Message.toObjectList(msg.getPermissionsList(),
    permission_pb.Permission.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.Session}
 */
proto.brilltech.maaser.entities.Session.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.Session;
  return proto.brilltech.maaser.entities.Session.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.Session} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.Session}
 */
proto.brilltech.maaser.entities.Session.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountid(value);
      break;
    case 3:
      var value = new treeleaf_pb.ClientDetail;
      reader.readMessage(value,treeleaf_pb.ClientDetail.deserializeBinaryFromReader);
      msg.setClientdetail(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setActive(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPushtoken(value);
      break;
    case 7:
      var value = /** @type {!proto.brilltech.maaser.entities.AccountType} */ (reader.readEnum());
      msg.setAccounttype(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setLoginid(value);
      break;
    case 9:
      var value = new account_pb.User;
      reader.readMessage(value,account_pb.User.deserializeBinaryFromReader);
      msg.setUser(value);
      break;
    case 10:
      var value = new account_pb.Client;
      reader.readMessage(value,account_pb.Client.deserializeBinaryFromReader);
      msg.setClient(value);
      break;
    case 11:
      var value = new account_pb.Employee;
      reader.readMessage(value,account_pb.Employee.deserializeBinaryFromReader);
      msg.setEmployee(value);
      break;
    case 12:
      var value = new permission_pb.Permission;
      reader.readMessage(value,permission_pb.Permission.deserializeBinaryFromReader);
      msg.addPermissions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.Session.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.Session.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.Session} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.Session.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSessionid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAccountid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getClientdetail();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      treeleaf_pb.ClientDetail.serializeBinaryToWriter
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getActive();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getPushtoken();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getAccounttype();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getLoginid();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getUser();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      account_pb.User.serializeBinaryToWriter
    );
  }
  f = message.getClient();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      account_pb.Client.serializeBinaryToWriter
    );
  }
  f = message.getEmployee();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      account_pb.Employee.serializeBinaryToWriter
    );
  }
  f = message.getPermissionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      permission_pb.Permission.serializeBinaryToWriter
    );
  }
};


/**
 * optional string sessionId = 1;
 * @return {string}
 */
proto.brilltech.maaser.entities.Session.prototype.getSessionid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Session} returns this
 */
proto.brilltech.maaser.entities.Session.prototype.setSessionid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string accountId = 2;
 * @return {string}
 */
proto.brilltech.maaser.entities.Session.prototype.getAccountid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Session} returns this
 */
proto.brilltech.maaser.entities.Session.prototype.setAccountid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional treeleaf.protos.ClientDetail clientDetail = 3;
 * @return {?proto.treeleaf.protos.ClientDetail}
 */
proto.brilltech.maaser.entities.Session.prototype.getClientdetail = function() {
  return /** @type{?proto.treeleaf.protos.ClientDetail} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.ClientDetail, 3));
};


/**
 * @param {?proto.treeleaf.protos.ClientDetail|undefined} value
 * @return {!proto.brilltech.maaser.entities.Session} returns this
*/
proto.brilltech.maaser.entities.Session.prototype.setClientdetail = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.entities.Session} returns this
 */
proto.brilltech.maaser.entities.Session.prototype.clearClientdetail = function() {
  return this.setClientdetail(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.entities.Session.prototype.hasClientdetail = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int64 timestamp = 4;
 * @return {number}
 */
proto.brilltech.maaser.entities.Session.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.entities.Session} returns this
 */
proto.brilltech.maaser.entities.Session.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional bool active = 5;
 * @return {boolean}
 */
proto.brilltech.maaser.entities.Session.prototype.getActive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.entities.Session} returns this
 */
proto.brilltech.maaser.entities.Session.prototype.setActive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional string pushToken = 6;
 * @return {string}
 */
proto.brilltech.maaser.entities.Session.prototype.getPushtoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Session} returns this
 */
proto.brilltech.maaser.entities.Session.prototype.setPushtoken = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional AccountType accountType = 7;
 * @return {!proto.brilltech.maaser.entities.AccountType}
 */
proto.brilltech.maaser.entities.Session.prototype.getAccounttype = function() {
  return /** @type {!proto.brilltech.maaser.entities.AccountType} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.brilltech.maaser.entities.AccountType} value
 * @return {!proto.brilltech.maaser.entities.Session} returns this
 */
proto.brilltech.maaser.entities.Session.prototype.setAccounttype = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional string loginId = 8;
 * @return {string}
 */
proto.brilltech.maaser.entities.Session.prototype.getLoginid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Session} returns this
 */
proto.brilltech.maaser.entities.Session.prototype.setLoginid = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional User user = 9;
 * @return {?proto.brilltech.maaser.entities.User}
 */
proto.brilltech.maaser.entities.Session.prototype.getUser = function() {
  return /** @type{?proto.brilltech.maaser.entities.User} */ (
    jspb.Message.getWrapperField(this, account_pb.User, 9));
};


/**
 * @param {?proto.brilltech.maaser.entities.User|undefined} value
 * @return {!proto.brilltech.maaser.entities.Session} returns this
*/
proto.brilltech.maaser.entities.Session.prototype.setUser = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.entities.Session} returns this
 */
proto.brilltech.maaser.entities.Session.prototype.clearUser = function() {
  return this.setUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.entities.Session.prototype.hasUser = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional Client client = 10;
 * @return {?proto.brilltech.maaser.entities.Client}
 */
proto.brilltech.maaser.entities.Session.prototype.getClient = function() {
  return /** @type{?proto.brilltech.maaser.entities.Client} */ (
    jspb.Message.getWrapperField(this, account_pb.Client, 10));
};


/**
 * @param {?proto.brilltech.maaser.entities.Client|undefined} value
 * @return {!proto.brilltech.maaser.entities.Session} returns this
*/
proto.brilltech.maaser.entities.Session.prototype.setClient = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.entities.Session} returns this
 */
proto.brilltech.maaser.entities.Session.prototype.clearClient = function() {
  return this.setClient(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.entities.Session.prototype.hasClient = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional Employee employee = 11;
 * @return {?proto.brilltech.maaser.entities.Employee}
 */
proto.brilltech.maaser.entities.Session.prototype.getEmployee = function() {
  return /** @type{?proto.brilltech.maaser.entities.Employee} */ (
    jspb.Message.getWrapperField(this, account_pb.Employee, 11));
};


/**
 * @param {?proto.brilltech.maaser.entities.Employee|undefined} value
 * @return {!proto.brilltech.maaser.entities.Session} returns this
*/
proto.brilltech.maaser.entities.Session.prototype.setEmployee = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.entities.Session} returns this
 */
proto.brilltech.maaser.entities.Session.prototype.clearEmployee = function() {
  return this.setEmployee(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.entities.Session.prototype.hasEmployee = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * repeated Permission permissions = 12;
 * @return {!Array<!proto.brilltech.maaser.entities.Permission>}
 */
proto.brilltech.maaser.entities.Session.prototype.getPermissionsList = function() {
  return /** @type{!Array<!proto.brilltech.maaser.entities.Permission>} */ (
    jspb.Message.getRepeatedWrapperField(this, permission_pb.Permission, 12));
};


/**
 * @param {!Array<!proto.brilltech.maaser.entities.Permission>} value
 * @return {!proto.brilltech.maaser.entities.Session} returns this
*/
proto.brilltech.maaser.entities.Session.prototype.setPermissionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.brilltech.maaser.entities.Permission=} opt_value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.Permission}
 */
proto.brilltech.maaser.entities.Session.prototype.addPermissions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.brilltech.maaser.entities.Permission, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.entities.Session} returns this
 */
proto.brilltech.maaser.entities.Session.prototype.clearPermissionsList = function() {
  return this.setPermissionsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.LoginRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.LoginRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.LoginRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.LoginRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    emailphone: jspb.Message.getFieldWithDefault(msg, 1, ""),
    password: jspb.Message.getFieldWithDefault(msg, 2, ""),
    clientdetail: (f = msg.getClientdetail()) && treeleaf_pb.ClientDetail.toObject(includeInstance, f),
    accounttype: jspb.Message.getFieldWithDefault(msg, 4, 0),
    pushtoken: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.LoginRequest}
 */
proto.brilltech.maaser.entities.LoginRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.LoginRequest;
  return proto.brilltech.maaser.entities.LoginRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.LoginRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.LoginRequest}
 */
proto.brilltech.maaser.entities.LoginRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmailphone(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    case 3:
      var value = new treeleaf_pb.ClientDetail;
      reader.readMessage(value,treeleaf_pb.ClientDetail.deserializeBinaryFromReader);
      msg.setClientdetail(value);
      break;
    case 4:
      var value = /** @type {!proto.brilltech.maaser.entities.AccountType} */ (reader.readEnum());
      msg.setAccounttype(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPushtoken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.LoginRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.LoginRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.LoginRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.LoginRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEmailphone();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getClientdetail();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      treeleaf_pb.ClientDetail.serializeBinaryToWriter
    );
  }
  f = message.getAccounttype();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getPushtoken();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string emailPhone = 1;
 * @return {string}
 */
proto.brilltech.maaser.entities.LoginRequest.prototype.getEmailphone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.LoginRequest} returns this
 */
proto.brilltech.maaser.entities.LoginRequest.prototype.setEmailphone = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string password = 2;
 * @return {string}
 */
proto.brilltech.maaser.entities.LoginRequest.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.LoginRequest} returns this
 */
proto.brilltech.maaser.entities.LoginRequest.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional treeleaf.protos.ClientDetail clientDetail = 3;
 * @return {?proto.treeleaf.protos.ClientDetail}
 */
proto.brilltech.maaser.entities.LoginRequest.prototype.getClientdetail = function() {
  return /** @type{?proto.treeleaf.protos.ClientDetail} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.ClientDetail, 3));
};


/**
 * @param {?proto.treeleaf.protos.ClientDetail|undefined} value
 * @return {!proto.brilltech.maaser.entities.LoginRequest} returns this
*/
proto.brilltech.maaser.entities.LoginRequest.prototype.setClientdetail = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.entities.LoginRequest} returns this
 */
proto.brilltech.maaser.entities.LoginRequest.prototype.clearClientdetail = function() {
  return this.setClientdetail(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.entities.LoginRequest.prototype.hasClientdetail = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional AccountType accountType = 4;
 * @return {!proto.brilltech.maaser.entities.AccountType}
 */
proto.brilltech.maaser.entities.LoginRequest.prototype.getAccounttype = function() {
  return /** @type {!proto.brilltech.maaser.entities.AccountType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.brilltech.maaser.entities.AccountType} value
 * @return {!proto.brilltech.maaser.entities.LoginRequest} returns this
 */
proto.brilltech.maaser.entities.LoginRequest.prototype.setAccounttype = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional string pushToken = 5;
 * @return {string}
 */
proto.brilltech.maaser.entities.LoginRequest.prototype.getPushtoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.LoginRequest} returns this
 */
proto.brilltech.maaser.entities.LoginRequest.prototype.setPushtoken = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.Authorization.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.Authorization.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.Authorization} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.Authorization.toObject = function(includeInstance, msg) {
  var f, obj = {
    token: jspb.Message.getFieldWithDefault(msg, 1, ""),
    permission: jspb.Message.getFieldWithDefault(msg, 2, ""),
    ip: jspb.Message.getFieldWithDefault(msg, 3, ""),
    user: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.Authorization}
 */
proto.brilltech.maaser.entities.Authorization.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.Authorization;
  return proto.brilltech.maaser.entities.Authorization.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.Authorization} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.Authorization}
 */
proto.brilltech.maaser.entities.Authorization.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPermission(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setIp(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setUser(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.Authorization.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.Authorization.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.Authorization} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.Authorization.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getToken();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPermission();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getIp();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getUser();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string token = 1;
 * @return {string}
 */
proto.brilltech.maaser.entities.Authorization.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Authorization} returns this
 */
proto.brilltech.maaser.entities.Authorization.prototype.setToken = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string permission = 2;
 * @return {string}
 */
proto.brilltech.maaser.entities.Authorization.prototype.getPermission = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Authorization} returns this
 */
proto.brilltech.maaser.entities.Authorization.prototype.setPermission = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string ip = 3;
 * @return {string}
 */
proto.brilltech.maaser.entities.Authorization.prototype.getIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Authorization} returns this
 */
proto.brilltech.maaser.entities.Authorization.prototype.setIp = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string user = 4;
 * @return {string}
 */
proto.brilltech.maaser.entities.Authorization.prototype.getUser = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Authorization} returns this
 */
proto.brilltech.maaser.entities.Authorization.prototype.setUser = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.AuthResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.AuthResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.AuthResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.AuthResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    granted: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    session: (f = msg.getSession()) && proto.brilltech.maaser.entities.Session.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.AuthResponse}
 */
proto.brilltech.maaser.entities.AuthResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.AuthResponse;
  return proto.brilltech.maaser.entities.AuthResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.AuthResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.AuthResponse}
 */
proto.brilltech.maaser.entities.AuthResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGranted(value);
      break;
    case 2:
      var value = new proto.brilltech.maaser.entities.Session;
      reader.readMessage(value,proto.brilltech.maaser.entities.Session.deserializeBinaryFromReader);
      msg.setSession(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.AuthResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.AuthResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.AuthResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.AuthResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGranted();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getSession();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.brilltech.maaser.entities.Session.serializeBinaryToWriter
    );
  }
};


/**
 * optional bool granted = 1;
 * @return {boolean}
 */
proto.brilltech.maaser.entities.AuthResponse.prototype.getGranted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.entities.AuthResponse} returns this
 */
proto.brilltech.maaser.entities.AuthResponse.prototype.setGranted = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional Session session = 2;
 * @return {?proto.brilltech.maaser.entities.Session}
 */
proto.brilltech.maaser.entities.AuthResponse.prototype.getSession = function() {
  return /** @type{?proto.brilltech.maaser.entities.Session} */ (
    jspb.Message.getWrapperField(this, proto.brilltech.maaser.entities.Session, 2));
};


/**
 * @param {?proto.brilltech.maaser.entities.Session|undefined} value
 * @return {!proto.brilltech.maaser.entities.AuthResponse} returns this
*/
proto.brilltech.maaser.entities.AuthResponse.prototype.setSession = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.entities.AuthResponse} returns this
 */
proto.brilltech.maaser.entities.AuthResponse.prototype.clearSession = function() {
  return this.setSession(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.entities.AuthResponse.prototype.hasSession = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.LoginResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.LoginResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.LoginResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.LoginResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    token: jspb.Message.getFieldWithDefault(msg, 1, ""),
    loginaccount: (f = msg.getLoginaccount()) && account_pb.LoginAccount.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.LoginResponse}
 */
proto.brilltech.maaser.entities.LoginResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.LoginResponse;
  return proto.brilltech.maaser.entities.LoginResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.LoginResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.LoginResponse}
 */
proto.brilltech.maaser.entities.LoginResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken(value);
      break;
    case 2:
      var value = new account_pb.LoginAccount;
      reader.readMessage(value,account_pb.LoginAccount.deserializeBinaryFromReader);
      msg.setLoginaccount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.LoginResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.LoginResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.LoginResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.LoginResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getToken();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLoginaccount();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      account_pb.LoginAccount.serializeBinaryToWriter
    );
  }
};


/**
 * optional string token = 1;
 * @return {string}
 */
proto.brilltech.maaser.entities.LoginResponse.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.LoginResponse} returns this
 */
proto.brilltech.maaser.entities.LoginResponse.prototype.setToken = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional LoginAccount loginAccount = 2;
 * @return {?proto.brilltech.maaser.entities.LoginAccount}
 */
proto.brilltech.maaser.entities.LoginResponse.prototype.getLoginaccount = function() {
  return /** @type{?proto.brilltech.maaser.entities.LoginAccount} */ (
    jspb.Message.getWrapperField(this, account_pb.LoginAccount, 2));
};


/**
 * @param {?proto.brilltech.maaser.entities.LoginAccount|undefined} value
 * @return {!proto.brilltech.maaser.entities.LoginResponse} returns this
*/
proto.brilltech.maaser.entities.LoginResponse.prototype.setLoginaccount = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.entities.LoginResponse} returns this
 */
proto.brilltech.maaser.entities.LoginResponse.prototype.clearLoginaccount = function() {
  return this.setLoginaccount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.entities.LoginResponse.prototype.hasLoginaccount = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.Jwt.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.Jwt.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.Jwt} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.Jwt.toObject = function(includeInstance, msg) {
  var f, obj = {
    signaturesecret: jspb.Message.getFieldWithDefault(msg, 1, ""),
    session: (f = msg.getSession()) && proto.brilltech.maaser.entities.Session.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.Jwt}
 */
proto.brilltech.maaser.entities.Jwt.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.Jwt;
  return proto.brilltech.maaser.entities.Jwt.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.Jwt} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.Jwt}
 */
proto.brilltech.maaser.entities.Jwt.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSignaturesecret(value);
      break;
    case 2:
      var value = new proto.brilltech.maaser.entities.Session;
      reader.readMessage(value,proto.brilltech.maaser.entities.Session.deserializeBinaryFromReader);
      msg.setSession(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.Jwt.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.Jwt.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.Jwt} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.Jwt.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSignaturesecret();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSession();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.brilltech.maaser.entities.Session.serializeBinaryToWriter
    );
  }
};


/**
 * optional string signatureSecret = 1;
 * @return {string}
 */
proto.brilltech.maaser.entities.Jwt.prototype.getSignaturesecret = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Jwt} returns this
 */
proto.brilltech.maaser.entities.Jwt.prototype.setSignaturesecret = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Session session = 2;
 * @return {?proto.brilltech.maaser.entities.Session}
 */
proto.brilltech.maaser.entities.Jwt.prototype.getSession = function() {
  return /** @type{?proto.brilltech.maaser.entities.Session} */ (
    jspb.Message.getWrapperField(this, proto.brilltech.maaser.entities.Session, 2));
};


/**
 * @param {?proto.brilltech.maaser.entities.Session|undefined} value
 * @return {!proto.brilltech.maaser.entities.Jwt} returns this
*/
proto.brilltech.maaser.entities.Jwt.prototype.setSession = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.entities.Jwt} returns this
 */
proto.brilltech.maaser.entities.Jwt.prototype.clearSession = function() {
  return this.setSession(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.entities.Jwt.prototype.hasSession = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.brilltech.maaser.entities.JwtLit.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.JwtLit.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.JwtLit.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.JwtLit} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.JwtLit.toObject = function(includeInstance, msg) {
  var f, obj = {
    jwtsList: jspb.Message.toObjectList(msg.getJwtsList(),
    proto.brilltech.maaser.entities.Jwt.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.JwtLit}
 */
proto.brilltech.maaser.entities.JwtLit.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.JwtLit;
  return proto.brilltech.maaser.entities.JwtLit.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.JwtLit} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.JwtLit}
 */
proto.brilltech.maaser.entities.JwtLit.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.brilltech.maaser.entities.Jwt;
      reader.readMessage(value,proto.brilltech.maaser.entities.Jwt.deserializeBinaryFromReader);
      msg.addJwts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.JwtLit.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.JwtLit.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.JwtLit} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.JwtLit.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getJwtsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.brilltech.maaser.entities.Jwt.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Jwt jwts = 1;
 * @return {!Array<!proto.brilltech.maaser.entities.Jwt>}
 */
proto.brilltech.maaser.entities.JwtLit.prototype.getJwtsList = function() {
  return /** @type{!Array<!proto.brilltech.maaser.entities.Jwt>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.brilltech.maaser.entities.Jwt, 1));
};


/**
 * @param {!Array<!proto.brilltech.maaser.entities.Jwt>} value
 * @return {!proto.brilltech.maaser.entities.JwtLit} returns this
*/
proto.brilltech.maaser.entities.JwtLit.prototype.setJwtsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.brilltech.maaser.entities.Jwt=} opt_value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.Jwt}
 */
proto.brilltech.maaser.entities.JwtLit.prototype.addJwts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.brilltech.maaser.entities.Jwt, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.entities.JwtLit} returns this
 */
proto.brilltech.maaser.entities.JwtLit.prototype.clearJwtsList = function() {
  return this.setJwtsList([]);
};


goog.object.extend(exports, proto.brilltech.maaser.entities);
