// source: campaign_rpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var treeleaf_pb = require('./treeleaf_pb.js');
goog.object.extend(proto, treeleaf_pb);
var campaign_pb = require('./campaign_pb.js');
goog.object.extend(proto, campaign_pb);
var auth_pb = require('./auth_pb.js');
goog.object.extend(proto, auth_pb);
goog.exportSymbol('proto.brilltech.maaser.rpc.CampaignBaseRequest', null, global);
goog.exportSymbol('proto.brilltech.maaser.rpc.CampaignBaseResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.brilltech.maaser.rpc.CampaignBaseRequest.repeatedFields_, null);
};
goog.inherits(proto.brilltech.maaser.rpc.CampaignBaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.rpc.CampaignBaseRequest.displayName = 'proto.brilltech.maaser.rpc.CampaignBaseRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.brilltech.maaser.rpc.CampaignBaseResponse.repeatedFields_, null);
};
goog.inherits(proto.brilltech.maaser.rpc.CampaignBaseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.rpc.CampaignBaseResponse.displayName = 'proto.brilltech.maaser.rpc.CampaignBaseResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.rpc.CampaignBaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.rpc.CampaignBaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    refid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    stringvalue: jspb.Message.getFieldWithDefault(msg, 2, ""),
    stringvaluesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    intvalue: jspb.Message.getFieldWithDefault(msg, 4, 0),
    longvalue: jspb.Message.getFieldWithDefault(msg, 5, 0),
    boolvalue: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    doublevalue: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    debug: (f = msg.getDebug()) && treeleaf_pb.Debug.toObject(includeInstance, f),
    authorization: (f = msg.getAuthorization()) && auth_pb.Authorization.toObject(includeInstance, f),
    campaign: (f = msg.getCampaign()) && campaign_pb.Campaign.toObject(includeInstance, f),
    subcampaign: (f = msg.getSubcampaign()) && campaign_pb.SubCampaign.toObject(includeInstance, f),
    campaignfilter: (f = msg.getCampaignfilter()) && campaign_pb.CampaignFilter.toObject(includeInstance, f),
    comment: (f = msg.getComment()) && campaign_pb.Comment.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.rpc.CampaignBaseRequest;
  return proto.brilltech.maaser.rpc.CampaignBaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.rpc.CampaignBaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRefid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringvalue(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addStringvalues(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIntvalue(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLongvalue(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBoolvalue(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDoublevalue(value);
      break;
    case 8:
      var value = new treeleaf_pb.Debug;
      reader.readMessage(value,treeleaf_pb.Debug.deserializeBinaryFromReader);
      msg.setDebug(value);
      break;
    case 9:
      var value = new auth_pb.Authorization;
      reader.readMessage(value,auth_pb.Authorization.deserializeBinaryFromReader);
      msg.setAuthorization(value);
      break;
    case 10:
      var value = new campaign_pb.Campaign;
      reader.readMessage(value,campaign_pb.Campaign.deserializeBinaryFromReader);
      msg.setCampaign(value);
      break;
    case 11:
      var value = new campaign_pb.SubCampaign;
      reader.readMessage(value,campaign_pb.SubCampaign.deserializeBinaryFromReader);
      msg.setSubcampaign(value);
      break;
    case 12:
      var value = new campaign_pb.CampaignFilter;
      reader.readMessage(value,campaign_pb.CampaignFilter.deserializeBinaryFromReader);
      msg.setCampaignfilter(value);
      break;
    case 13:
      var value = new campaign_pb.Comment;
      reader.readMessage(value,campaign_pb.Comment.deserializeBinaryFromReader);
      msg.setComment(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.rpc.CampaignBaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.rpc.CampaignBaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRefid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStringvalue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStringvaluesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getIntvalue();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getLongvalue();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getBoolvalue();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getDoublevalue();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getDebug();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      treeleaf_pb.Debug.serializeBinaryToWriter
    );
  }
  f = message.getAuthorization();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      auth_pb.Authorization.serializeBinaryToWriter
    );
  }
  f = message.getCampaign();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      campaign_pb.Campaign.serializeBinaryToWriter
    );
  }
  f = message.getSubcampaign();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      campaign_pb.SubCampaign.serializeBinaryToWriter
    );
  }
  f = message.getCampaignfilter();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      campaign_pb.CampaignFilter.serializeBinaryToWriter
    );
  }
  f = message.getComment();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      campaign_pb.Comment.serializeBinaryToWriter
    );
  }
};


/**
 * optional string refId = 1;
 * @return {string}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.getRefid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.setRefid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string stringValue = 2;
 * @return {string}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.getStringvalue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.setStringvalue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string stringValues = 3;
 * @return {!Array<string>}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.getStringvaluesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.setStringvaluesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.addStringvalues = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.clearStringvaluesList = function() {
  return this.setStringvaluesList([]);
};


/**
 * optional int32 intValue = 4;
 * @return {number}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.getIntvalue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.setIntvalue = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 longValue = 5;
 * @return {number}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.getLongvalue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.setLongvalue = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional bool boolValue = 6;
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.getBoolvalue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.setBoolvalue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool doubleValue = 7;
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.getDoublevalue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.setDoublevalue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional treeleaf.protos.Debug debug = 8;
 * @return {?proto.treeleaf.protos.Debug}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.getDebug = function() {
  return /** @type{?proto.treeleaf.protos.Debug} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.Debug, 8));
};


/**
 * @param {?proto.treeleaf.protos.Debug|undefined} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.setDebug = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.clearDebug = function() {
  return this.setDebug(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.hasDebug = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional brilltech.maaser.entities.Authorization authorization = 9;
 * @return {?proto.brilltech.maaser.entities.Authorization}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.getAuthorization = function() {
  return /** @type{?proto.brilltech.maaser.entities.Authorization} */ (
    jspb.Message.getWrapperField(this, auth_pb.Authorization, 9));
};


/**
 * @param {?proto.brilltech.maaser.entities.Authorization|undefined} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.setAuthorization = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.clearAuthorization = function() {
  return this.setAuthorization(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.hasAuthorization = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional brilltech.maaser.entities.Campaign campaign = 10;
 * @return {?proto.brilltech.maaser.entities.Campaign}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.getCampaign = function() {
  return /** @type{?proto.brilltech.maaser.entities.Campaign} */ (
    jspb.Message.getWrapperField(this, campaign_pb.Campaign, 10));
};


/**
 * @param {?proto.brilltech.maaser.entities.Campaign|undefined} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.setCampaign = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.clearCampaign = function() {
  return this.setCampaign(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.hasCampaign = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional brilltech.maaser.entities.SubCampaign subCampaign = 11;
 * @return {?proto.brilltech.maaser.entities.SubCampaign}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.getSubcampaign = function() {
  return /** @type{?proto.brilltech.maaser.entities.SubCampaign} */ (
    jspb.Message.getWrapperField(this, campaign_pb.SubCampaign, 11));
};


/**
 * @param {?proto.brilltech.maaser.entities.SubCampaign|undefined} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.setSubcampaign = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.clearSubcampaign = function() {
  return this.setSubcampaign(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.hasSubcampaign = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional brilltech.maaser.entities.CampaignFilter campaignFilter = 12;
 * @return {?proto.brilltech.maaser.entities.CampaignFilter}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.getCampaignfilter = function() {
  return /** @type{?proto.brilltech.maaser.entities.CampaignFilter} */ (
    jspb.Message.getWrapperField(this, campaign_pb.CampaignFilter, 12));
};


/**
 * @param {?proto.brilltech.maaser.entities.CampaignFilter|undefined} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.setCampaignfilter = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.clearCampaignfilter = function() {
  return this.setCampaignfilter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.hasCampaignfilter = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional brilltech.maaser.entities.Comment comment = 13;
 * @return {?proto.brilltech.maaser.entities.Comment}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.getComment = function() {
  return /** @type{?proto.brilltech.maaser.entities.Comment} */ (
    jspb.Message.getWrapperField(this, campaign_pb.Comment, 13));
};


/**
 * @param {?proto.brilltech.maaser.entities.Comment|undefined} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.setComment = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.clearComment = function() {
  return this.setComment(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.CampaignBaseRequest.prototype.hasComment = function() {
  return jspb.Message.getField(this, 13) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.repeatedFields_ = [8,10,12];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.rpc.CampaignBaseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.rpc.CampaignBaseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    error: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    msg: jspb.Message.getFieldWithDefault(msg, 2, ""),
    errorcode: jspb.Message.getFieldWithDefault(msg, 3, 0),
    success: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    timestamp: jspb.Message.getFieldWithDefault(msg, 5, 0),
    debug: (f = msg.getDebug()) && treeleaf_pb.Debug.toObject(includeInstance, f),
    campaign: (f = msg.getCampaign()) && campaign_pb.Campaign.toObject(includeInstance, f),
    campaignsList: jspb.Message.toObjectList(msg.getCampaignsList(),
    campaign_pb.Campaign.toObject, includeInstance),
    subcampaign: (f = msg.getSubcampaign()) && campaign_pb.SubCampaign.toObject(includeInstance, f),
    subcampaignsList: jspb.Message.toObjectList(msg.getSubcampaignsList(),
    campaign_pb.SubCampaign.toObject, includeInstance),
    comment: (f = msg.getComment()) && campaign_pb.Comment.toObject(includeInstance, f),
    commentsList: jspb.Message.toObjectList(msg.getCommentsList(),
    campaign_pb.Comment.toObject, includeInstance),
    campaignurl: jspb.Message.getFieldWithDefault(msg, 13, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.rpc.CampaignBaseResponse;
  return proto.brilltech.maaser.rpc.CampaignBaseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.rpc.CampaignBaseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setError(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsg(value);
      break;
    case 3:
      var value = /** @type {!proto.treeleaf.protos.ErrorCode} */ (reader.readEnum());
      msg.setErrorcode(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 6:
      var value = new treeleaf_pb.Debug;
      reader.readMessage(value,treeleaf_pb.Debug.deserializeBinaryFromReader);
      msg.setDebug(value);
      break;
    case 7:
      var value = new campaign_pb.Campaign;
      reader.readMessage(value,campaign_pb.Campaign.deserializeBinaryFromReader);
      msg.setCampaign(value);
      break;
    case 8:
      var value = new campaign_pb.Campaign;
      reader.readMessage(value,campaign_pb.Campaign.deserializeBinaryFromReader);
      msg.addCampaigns(value);
      break;
    case 9:
      var value = new campaign_pb.SubCampaign;
      reader.readMessage(value,campaign_pb.SubCampaign.deserializeBinaryFromReader);
      msg.setSubcampaign(value);
      break;
    case 10:
      var value = new campaign_pb.SubCampaign;
      reader.readMessage(value,campaign_pb.SubCampaign.deserializeBinaryFromReader);
      msg.addSubcampaigns(value);
      break;
    case 11:
      var value = new campaign_pb.Comment;
      reader.readMessage(value,campaign_pb.Comment.deserializeBinaryFromReader);
      msg.setComment(value);
      break;
    case 12:
      var value = new campaign_pb.Comment;
      reader.readMessage(value,campaign_pb.Comment.deserializeBinaryFromReader);
      msg.addComments(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setCampaignurl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.rpc.CampaignBaseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.rpc.CampaignBaseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getError();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMsg();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getErrorcode();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getDebug();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      treeleaf_pb.Debug.serializeBinaryToWriter
    );
  }
  f = message.getCampaign();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      campaign_pb.Campaign.serializeBinaryToWriter
    );
  }
  f = message.getCampaignsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      campaign_pb.Campaign.serializeBinaryToWriter
    );
  }
  f = message.getSubcampaign();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      campaign_pb.SubCampaign.serializeBinaryToWriter
    );
  }
  f = message.getSubcampaignsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      campaign_pb.SubCampaign.serializeBinaryToWriter
    );
  }
  f = message.getComment();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      campaign_pb.Comment.serializeBinaryToWriter
    );
  }
  f = message.getCommentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      campaign_pb.Comment.serializeBinaryToWriter
    );
  }
  f = message.getCampaignurl();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
};


/**
 * optional bool error = 1;
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.getError = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.setError = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string msg = 2;
 * @return {string}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.getMsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.setMsg = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional treeleaf.protos.ErrorCode errorCode = 3;
 * @return {!proto.treeleaf.protos.ErrorCode}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.getErrorcode = function() {
  return /** @type {!proto.treeleaf.protos.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.treeleaf.protos.ErrorCode} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.setErrorcode = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional bool success = 4;
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional int64 timestamp = 5;
 * @return {number}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional treeleaf.protos.Debug debug = 6;
 * @return {?proto.treeleaf.protos.Debug}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.getDebug = function() {
  return /** @type{?proto.treeleaf.protos.Debug} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.Debug, 6));
};


/**
 * @param {?proto.treeleaf.protos.Debug|undefined} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.setDebug = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.clearDebug = function() {
  return this.setDebug(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.hasDebug = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional brilltech.maaser.entities.Campaign campaign = 7;
 * @return {?proto.brilltech.maaser.entities.Campaign}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.getCampaign = function() {
  return /** @type{?proto.brilltech.maaser.entities.Campaign} */ (
    jspb.Message.getWrapperField(this, campaign_pb.Campaign, 7));
};


/**
 * @param {?proto.brilltech.maaser.entities.Campaign|undefined} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.setCampaign = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.clearCampaign = function() {
  return this.setCampaign(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.hasCampaign = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * repeated brilltech.maaser.entities.Campaign campaigns = 8;
 * @return {!Array<!proto.brilltech.maaser.entities.Campaign>}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.getCampaignsList = function() {
  return /** @type{!Array<!proto.brilltech.maaser.entities.Campaign>} */ (
    jspb.Message.getRepeatedWrapperField(this, campaign_pb.Campaign, 8));
};


/**
 * @param {!Array<!proto.brilltech.maaser.entities.Campaign>} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.setCampaignsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.brilltech.maaser.entities.Campaign=} opt_value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.Campaign}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.addCampaigns = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.brilltech.maaser.entities.Campaign, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.clearCampaignsList = function() {
  return this.setCampaignsList([]);
};


/**
 * optional brilltech.maaser.entities.SubCampaign subCampaign = 9;
 * @return {?proto.brilltech.maaser.entities.SubCampaign}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.getSubcampaign = function() {
  return /** @type{?proto.brilltech.maaser.entities.SubCampaign} */ (
    jspb.Message.getWrapperField(this, campaign_pb.SubCampaign, 9));
};


/**
 * @param {?proto.brilltech.maaser.entities.SubCampaign|undefined} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.setSubcampaign = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.clearSubcampaign = function() {
  return this.setSubcampaign(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.hasSubcampaign = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * repeated brilltech.maaser.entities.SubCampaign subCampaigns = 10;
 * @return {!Array<!proto.brilltech.maaser.entities.SubCampaign>}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.getSubcampaignsList = function() {
  return /** @type{!Array<!proto.brilltech.maaser.entities.SubCampaign>} */ (
    jspb.Message.getRepeatedWrapperField(this, campaign_pb.SubCampaign, 10));
};


/**
 * @param {!Array<!proto.brilltech.maaser.entities.SubCampaign>} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.setSubcampaignsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.brilltech.maaser.entities.SubCampaign=} opt_value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.SubCampaign}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.addSubcampaigns = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.brilltech.maaser.entities.SubCampaign, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.clearSubcampaignsList = function() {
  return this.setSubcampaignsList([]);
};


/**
 * optional brilltech.maaser.entities.Comment comment = 11;
 * @return {?proto.brilltech.maaser.entities.Comment}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.getComment = function() {
  return /** @type{?proto.brilltech.maaser.entities.Comment} */ (
    jspb.Message.getWrapperField(this, campaign_pb.Comment, 11));
};


/**
 * @param {?proto.brilltech.maaser.entities.Comment|undefined} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.setComment = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.clearComment = function() {
  return this.setComment(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.hasComment = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * repeated brilltech.maaser.entities.Comment comments = 12;
 * @return {!Array<!proto.brilltech.maaser.entities.Comment>}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.getCommentsList = function() {
  return /** @type{!Array<!proto.brilltech.maaser.entities.Comment>} */ (
    jspb.Message.getRepeatedWrapperField(this, campaign_pb.Comment, 12));
};


/**
 * @param {!Array<!proto.brilltech.maaser.entities.Comment>} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.setCommentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.brilltech.maaser.entities.Comment=} opt_value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.Comment}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.addComments = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.brilltech.maaser.entities.Comment, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.clearCommentsList = function() {
  return this.setCommentsList([]);
};


/**
 * optional string campaignUrl = 13;
 * @return {string}
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.getCampaignurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.rpc.CampaignBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.CampaignBaseResponse.prototype.setCampaignurl = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


goog.object.extend(exports, proto.brilltech.maaser.rpc);
