// source: campaign.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var account_pb = require('./account_pb.js');
goog.object.extend(proto, account_pb);
var treeleaf_pb = require('./treeleaf_pb.js');
goog.object.extend(proto, treeleaf_pb);
goog.exportSymbol('proto.brilltech.maaser.entities.Campaign', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.Campaign.BeneficiaryType', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.CampaignFilter', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.CampaignStatus', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.Comment', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.SubCampaign', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.Campaign = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.brilltech.maaser.entities.Campaign.repeatedFields_, null);
};
goog.inherits(proto.brilltech.maaser.entities.Campaign, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.entities.Campaign.displayName = 'proto.brilltech.maaser.entities.Campaign';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.SubCampaign = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.brilltech.maaser.entities.SubCampaign, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.entities.SubCampaign.displayName = 'proto.brilltech.maaser.entities.SubCampaign';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.CampaignFilter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.brilltech.maaser.entities.CampaignFilter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.entities.CampaignFilter.displayName = 'proto.brilltech.maaser.entities.CampaignFilter';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.Comment = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.brilltech.maaser.entities.Comment, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.entities.Comment.displayName = 'proto.brilltech.maaser.entities.Comment';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.brilltech.maaser.entities.Campaign.repeatedFields_ = [13];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.Campaign.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.Campaign.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.Campaign} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.Campaign.toObject = function(includeInstance, msg) {
  var f, obj = {
    campaignid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    targetamount: jspb.Message.getFieldWithDefault(msg, 2, 0),
    countrycode: jspb.Message.getFieldWithDefault(msg, 3, ""),
    title: jspb.Message.getFieldWithDefault(msg, 4, ""),
    beneficiarytype: jspb.Message.getFieldWithDefault(msg, 5, 0),
    beneficiaryaccountid: jspb.Message.getFieldWithDefault(msg, 6, ""),
    category: jspb.Message.getFieldWithDefault(msg, 7, ""),
    description: jspb.Message.getFieldWithDefault(msg, 8, ""),
    collectedamount: jspb.Message.getFieldWithDefault(msg, 9, 0),
    thumbnailurl: jspb.Message.getFieldWithDefault(msg, 10, ""),
    accountid: jspb.Message.getFieldWithDefault(msg, 11, ""),
    allowsubcampaign: jspb.Message.getBooleanFieldWithDefault(msg, 12, false),
    subcampaignsList: jspb.Message.toObjectList(msg.getSubcampaignsList(),
    proto.brilltech.maaser.entities.SubCampaign.toObject, includeInstance),
    campaignstatus: jspb.Message.getFieldWithDefault(msg, 14, 0),
    campaignstarter: (f = msg.getCampaignstarter()) && account_pb.Client.toObject(includeInstance, f),
    campaignbeneficiary: (f = msg.getCampaignbeneficiary()) && account_pb.Client.toObject(includeInstance, f),
    createdat: jspb.Message.getFieldWithDefault(msg, 17, 0),
    updatedat: jspb.Message.getFieldWithDefault(msg, 18, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.Campaign}
 */
proto.brilltech.maaser.entities.Campaign.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.Campaign;
  return proto.brilltech.maaser.entities.Campaign.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.Campaign} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.Campaign}
 */
proto.brilltech.maaser.entities.Campaign.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCampaignid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTargetamount(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCountrycode(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 5:
      var value = /** @type {!proto.brilltech.maaser.entities.Campaign.BeneficiaryType} */ (reader.readEnum());
      msg.setBeneficiarytype(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setBeneficiaryaccountid(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategory(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCollectedamount(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setThumbnailurl(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountid(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAllowsubcampaign(value);
      break;
    case 13:
      var value = new proto.brilltech.maaser.entities.SubCampaign;
      reader.readMessage(value,proto.brilltech.maaser.entities.SubCampaign.deserializeBinaryFromReader);
      msg.addSubcampaigns(value);
      break;
    case 14:
      var value = /** @type {!proto.brilltech.maaser.entities.CampaignStatus} */ (reader.readEnum());
      msg.setCampaignstatus(value);
      break;
    case 15:
      var value = new account_pb.Client;
      reader.readMessage(value,account_pb.Client.deserializeBinaryFromReader);
      msg.setCampaignstarter(value);
      break;
    case 16:
      var value = new account_pb.Client;
      reader.readMessage(value,account_pb.Client.deserializeBinaryFromReader);
      msg.setCampaignbeneficiary(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedat(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdatedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.Campaign.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.Campaign.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.Campaign} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.Campaign.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCampaignid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTargetamount();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getCountrycode();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getBeneficiarytype();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getBeneficiaryaccountid();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCategory();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getCollectedamount();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getThumbnailurl();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getAccountid();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getAllowsubcampaign();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
  f = message.getSubcampaignsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      proto.brilltech.maaser.entities.SubCampaign.serializeBinaryToWriter
    );
  }
  f = message.getCampaignstatus();
  if (f !== 0.0) {
    writer.writeEnum(
      14,
      f
    );
  }
  f = message.getCampaignstarter();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      account_pb.Client.serializeBinaryToWriter
    );
  }
  f = message.getCampaignbeneficiary();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      account_pb.Client.serializeBinaryToWriter
    );
  }
  f = message.getCreatedat();
  if (f !== 0) {
    writer.writeInt64(
      17,
      f
    );
  }
  f = message.getUpdatedat();
  if (f !== 0) {
    writer.writeInt64(
      18,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.brilltech.maaser.entities.Campaign.BeneficiaryType = {
  UNKNOWN_BENEFICIARY: 0,
  MYSELF: 1,
  OTHERS: 2
};

/**
 * optional string campaignId = 1;
 * @return {string}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getCampaignid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.setCampaignid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 targetAmount = 2;
 * @return {number}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getTargetamount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.setTargetamount = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string countryCode = 3;
 * @return {string}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getCountrycode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.setCountrycode = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string title = 4;
 * @return {string}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional BeneficiaryType beneficiaryType = 5;
 * @return {!proto.brilltech.maaser.entities.Campaign.BeneficiaryType}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getBeneficiarytype = function() {
  return /** @type {!proto.brilltech.maaser.entities.Campaign.BeneficiaryType} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.brilltech.maaser.entities.Campaign.BeneficiaryType} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.setBeneficiarytype = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional string beneficiaryAccountId = 6;
 * @return {string}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getBeneficiaryaccountid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.setBeneficiaryaccountid = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string category = 7;
 * @return {string}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.setCategory = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string description = 8;
 * @return {string}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional int64 collectedAmount = 9;
 * @return {number}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getCollectedamount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.setCollectedamount = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional string thumbnailUrl = 10;
 * @return {string}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getThumbnailurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.setThumbnailurl = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string accountId = 11;
 * @return {string}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getAccountid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.setAccountid = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional bool allowSubCampaign = 12;
 * @return {boolean}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getAllowsubcampaign = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.setAllowsubcampaign = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value);
};


/**
 * repeated SubCampaign subCampaigns = 13;
 * @return {!Array<!proto.brilltech.maaser.entities.SubCampaign>}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getSubcampaignsList = function() {
  return /** @type{!Array<!proto.brilltech.maaser.entities.SubCampaign>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.brilltech.maaser.entities.SubCampaign, 13));
};


/**
 * @param {!Array<!proto.brilltech.maaser.entities.SubCampaign>} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
*/
proto.brilltech.maaser.entities.Campaign.prototype.setSubcampaignsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.brilltech.maaser.entities.SubCampaign=} opt_value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.SubCampaign}
 */
proto.brilltech.maaser.entities.Campaign.prototype.addSubcampaigns = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.brilltech.maaser.entities.SubCampaign, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.clearSubcampaignsList = function() {
  return this.setSubcampaignsList([]);
};


/**
 * optional CampaignStatus campaignStatus = 14;
 * @return {!proto.brilltech.maaser.entities.CampaignStatus}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getCampaignstatus = function() {
  return /** @type {!proto.brilltech.maaser.entities.CampaignStatus} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {!proto.brilltech.maaser.entities.CampaignStatus} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.setCampaignstatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 14, value);
};


/**
 * optional Client campaignStarter = 15;
 * @return {?proto.brilltech.maaser.entities.Client}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getCampaignstarter = function() {
  return /** @type{?proto.brilltech.maaser.entities.Client} */ (
    jspb.Message.getWrapperField(this, account_pb.Client, 15));
};


/**
 * @param {?proto.brilltech.maaser.entities.Client|undefined} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
*/
proto.brilltech.maaser.entities.Campaign.prototype.setCampaignstarter = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.clearCampaignstarter = function() {
  return this.setCampaignstarter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.entities.Campaign.prototype.hasCampaignstarter = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional Client campaignBeneficiary = 16;
 * @return {?proto.brilltech.maaser.entities.Client}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getCampaignbeneficiary = function() {
  return /** @type{?proto.brilltech.maaser.entities.Client} */ (
    jspb.Message.getWrapperField(this, account_pb.Client, 16));
};


/**
 * @param {?proto.brilltech.maaser.entities.Client|undefined} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
*/
proto.brilltech.maaser.entities.Campaign.prototype.setCampaignbeneficiary = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.clearCampaignbeneficiary = function() {
  return this.setCampaignbeneficiary(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.entities.Campaign.prototype.hasCampaignbeneficiary = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional int64 createdAt = 17;
 * @return {number}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getCreatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 17, value);
};


/**
 * optional int64 updatedAt = 18;
 * @return {number}
 */
proto.brilltech.maaser.entities.Campaign.prototype.getUpdatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.entities.Campaign} returns this
 */
proto.brilltech.maaser.entities.Campaign.prototype.setUpdatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 18, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.SubCampaign.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.SubCampaign} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.SubCampaign.toObject = function(includeInstance, msg) {
  var f, obj = {
    subcampaignid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    targetamount: jspb.Message.getFieldWithDefault(msg, 2, 0),
    collectedamount: jspb.Message.getFieldWithDefault(msg, 3, 0),
    campaignid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    accountid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    campaign: (f = msg.getCampaign()) && proto.brilltech.maaser.entities.Campaign.toObject(includeInstance, f),
    subcampaignstatus: jspb.Message.getFieldWithDefault(msg, 7, 0),
    subcampaignstarter: (f = msg.getSubcampaignstarter()) && account_pb.Client.toObject(includeInstance, f),
    createdat: jspb.Message.getFieldWithDefault(msg, 9, 0),
    updatedat: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.SubCampaign}
 */
proto.brilltech.maaser.entities.SubCampaign.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.SubCampaign;
  return proto.brilltech.maaser.entities.SubCampaign.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.SubCampaign} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.SubCampaign}
 */
proto.brilltech.maaser.entities.SubCampaign.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubcampaignid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTargetamount(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCollectedamount(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCampaignid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountid(value);
      break;
    case 6:
      var value = new proto.brilltech.maaser.entities.Campaign;
      reader.readMessage(value,proto.brilltech.maaser.entities.Campaign.deserializeBinaryFromReader);
      msg.setCampaign(value);
      break;
    case 7:
      var value = /** @type {!proto.brilltech.maaser.entities.CampaignStatus} */ (reader.readEnum());
      msg.setSubcampaignstatus(value);
      break;
    case 8:
      var value = new account_pb.Client;
      reader.readMessage(value,account_pb.Client.deserializeBinaryFromReader);
      msg.setSubcampaignstarter(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedat(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdatedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.SubCampaign.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.SubCampaign} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.SubCampaign.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSubcampaignid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTargetamount();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getCollectedamount();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getCampaignid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAccountid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCampaign();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.brilltech.maaser.entities.Campaign.serializeBinaryToWriter
    );
  }
  f = message.getSubcampaignstatus();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getSubcampaignstarter();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      account_pb.Client.serializeBinaryToWriter
    );
  }
  f = message.getCreatedat();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getUpdatedat();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
};


/**
 * optional string subCampaignId = 1;
 * @return {string}
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.getSubcampaignid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.SubCampaign} returns this
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.setSubcampaignid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 targetAmount = 2;
 * @return {number}
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.getTargetamount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.entities.SubCampaign} returns this
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.setTargetamount = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 collectedAmount = 3;
 * @return {number}
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.getCollectedamount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.entities.SubCampaign} returns this
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.setCollectedamount = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string campaignId = 4;
 * @return {string}
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.getCampaignid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.SubCampaign} returns this
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.setCampaignid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string accountId = 5;
 * @return {string}
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.getAccountid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.SubCampaign} returns this
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.setAccountid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional Campaign campaign = 6;
 * @return {?proto.brilltech.maaser.entities.Campaign}
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.getCampaign = function() {
  return /** @type{?proto.brilltech.maaser.entities.Campaign} */ (
    jspb.Message.getWrapperField(this, proto.brilltech.maaser.entities.Campaign, 6));
};


/**
 * @param {?proto.brilltech.maaser.entities.Campaign|undefined} value
 * @return {!proto.brilltech.maaser.entities.SubCampaign} returns this
*/
proto.brilltech.maaser.entities.SubCampaign.prototype.setCampaign = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.entities.SubCampaign} returns this
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.clearCampaign = function() {
  return this.setCampaign(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.hasCampaign = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional CampaignStatus subCampaignStatus = 7;
 * @return {!proto.brilltech.maaser.entities.CampaignStatus}
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.getSubcampaignstatus = function() {
  return /** @type {!proto.brilltech.maaser.entities.CampaignStatus} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.brilltech.maaser.entities.CampaignStatus} value
 * @return {!proto.brilltech.maaser.entities.SubCampaign} returns this
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.setSubcampaignstatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional Client subCampaignStarter = 8;
 * @return {?proto.brilltech.maaser.entities.Client}
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.getSubcampaignstarter = function() {
  return /** @type{?proto.brilltech.maaser.entities.Client} */ (
    jspb.Message.getWrapperField(this, account_pb.Client, 8));
};


/**
 * @param {?proto.brilltech.maaser.entities.Client|undefined} value
 * @return {!proto.brilltech.maaser.entities.SubCampaign} returns this
*/
proto.brilltech.maaser.entities.SubCampaign.prototype.setSubcampaignstarter = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.entities.SubCampaign} returns this
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.clearSubcampaignstarter = function() {
  return this.setSubcampaignstarter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.hasSubcampaignstarter = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional int64 createdAt = 9;
 * @return {number}
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.getCreatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.entities.SubCampaign} returns this
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int64 updatedAt = 10;
 * @return {number}
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.getUpdatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.entities.SubCampaign} returns this
 */
proto.brilltech.maaser.entities.SubCampaign.prototype.setUpdatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.CampaignFilter.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.CampaignFilter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.CampaignFilter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.CampaignFilter.toObject = function(includeInstance, msg) {
  var f, obj = {
    dataquery: (f = msg.getDataquery()) && treeleaf_pb.DataQuery.toObject(includeInstance, f),
    campaignstatus: jspb.Message.getFieldWithDefault(msg, 2, 0),
    countrycode: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.CampaignFilter}
 */
proto.brilltech.maaser.entities.CampaignFilter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.CampaignFilter;
  return proto.brilltech.maaser.entities.CampaignFilter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.CampaignFilter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.CampaignFilter}
 */
proto.brilltech.maaser.entities.CampaignFilter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new treeleaf_pb.DataQuery;
      reader.readMessage(value,treeleaf_pb.DataQuery.deserializeBinaryFromReader);
      msg.setDataquery(value);
      break;
    case 2:
      var value = /** @type {!proto.brilltech.maaser.entities.CampaignStatus} */ (reader.readEnum());
      msg.setCampaignstatus(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCountrycode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.CampaignFilter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.CampaignFilter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.CampaignFilter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.CampaignFilter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDataquery();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      treeleaf_pb.DataQuery.serializeBinaryToWriter
    );
  }
  f = message.getCampaignstatus();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getCountrycode();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional treeleaf.protos.DataQuery dataQuery = 1;
 * @return {?proto.treeleaf.protos.DataQuery}
 */
proto.brilltech.maaser.entities.CampaignFilter.prototype.getDataquery = function() {
  return /** @type{?proto.treeleaf.protos.DataQuery} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.DataQuery, 1));
};


/**
 * @param {?proto.treeleaf.protos.DataQuery|undefined} value
 * @return {!proto.brilltech.maaser.entities.CampaignFilter} returns this
*/
proto.brilltech.maaser.entities.CampaignFilter.prototype.setDataquery = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.entities.CampaignFilter} returns this
 */
proto.brilltech.maaser.entities.CampaignFilter.prototype.clearDataquery = function() {
  return this.setDataquery(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.entities.CampaignFilter.prototype.hasDataquery = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional CampaignStatus campaignStatus = 2;
 * @return {!proto.brilltech.maaser.entities.CampaignStatus}
 */
proto.brilltech.maaser.entities.CampaignFilter.prototype.getCampaignstatus = function() {
  return /** @type {!proto.brilltech.maaser.entities.CampaignStatus} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.brilltech.maaser.entities.CampaignStatus} value
 * @return {!proto.brilltech.maaser.entities.CampaignFilter} returns this
 */
proto.brilltech.maaser.entities.CampaignFilter.prototype.setCampaignstatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string countryCode = 3;
 * @return {string}
 */
proto.brilltech.maaser.entities.CampaignFilter.prototype.getCountrycode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.CampaignFilter} returns this
 */
proto.brilltech.maaser.entities.CampaignFilter.prototype.setCountrycode = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.Comment.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.Comment.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.Comment} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.Comment.toObject = function(includeInstance, msg) {
  var f, obj = {
    commentid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    description: jspb.Message.getFieldWithDefault(msg, 2, ""),
    refid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    addedby: jspb.Message.getFieldWithDefault(msg, 4, ""),
    fullname: jspb.Message.getFieldWithDefault(msg, 5, ""),
    profilepicture: jspb.Message.getFieldWithDefault(msg, 6, ""),
    createdat: jspb.Message.getFieldWithDefault(msg, 7, 0),
    updatedat: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.Comment}
 */
proto.brilltech.maaser.entities.Comment.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.Comment;
  return proto.brilltech.maaser.entities.Comment.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.Comment} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.Comment}
 */
proto.brilltech.maaser.entities.Comment.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCommentid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRefid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddedby(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setFullname(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setProfilepicture(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedat(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdatedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.Comment.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.Comment.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.Comment} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.Comment.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommentid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRefid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAddedby();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getFullname();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getProfilepicture();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCreatedat();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getUpdatedat();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
};


/**
 * optional string commentId = 1;
 * @return {string}
 */
proto.brilltech.maaser.entities.Comment.prototype.getCommentid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Comment} returns this
 */
proto.brilltech.maaser.entities.Comment.prototype.setCommentid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.brilltech.maaser.entities.Comment.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Comment} returns this
 */
proto.brilltech.maaser.entities.Comment.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string refId = 3;
 * @return {string}
 */
proto.brilltech.maaser.entities.Comment.prototype.getRefid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Comment} returns this
 */
proto.brilltech.maaser.entities.Comment.prototype.setRefid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string addedBy = 4;
 * @return {string}
 */
proto.brilltech.maaser.entities.Comment.prototype.getAddedby = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Comment} returns this
 */
proto.brilltech.maaser.entities.Comment.prototype.setAddedby = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string fullName = 5;
 * @return {string}
 */
proto.brilltech.maaser.entities.Comment.prototype.getFullname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Comment} returns this
 */
proto.brilltech.maaser.entities.Comment.prototype.setFullname = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string profilePicture = 6;
 * @return {string}
 */
proto.brilltech.maaser.entities.Comment.prototype.getProfilepicture = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Comment} returns this
 */
proto.brilltech.maaser.entities.Comment.prototype.setProfilepicture = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int64 createdAt = 7;
 * @return {number}
 */
proto.brilltech.maaser.entities.Comment.prototype.getCreatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.entities.Comment} returns this
 */
proto.brilltech.maaser.entities.Comment.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int64 updatedAt = 8;
 * @return {number}
 */
proto.brilltech.maaser.entities.Comment.prototype.getUpdatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.entities.Comment} returns this
 */
proto.brilltech.maaser.entities.Comment.prototype.setUpdatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * @enum {number}
 */
proto.brilltech.maaser.entities.CampaignStatus = {
  UNKNOWN_CAMPAIGN_STATUS: 0,
  OPEN: 1,
  CLOSED: 2,
  DISABLED_CAMPAIGN: 3
};

goog.object.extend(exports, proto.brilltech.maaser.entities);
