// source: notification.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.brilltech.maaser.entities.DeliveryDeviceType', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.EmailRequest', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.EmailType', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.Notification', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.NotificationRequest', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.NotificationRequestMode', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.NotificationType', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.PushNotificationRequest', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.Recipient', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.RecipientType', null, global);
goog.exportSymbol('proto.brilltech.maaser.entities.SmsRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.SmsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.brilltech.maaser.entities.SmsRequest.repeatedFields_, null);
};
goog.inherits(proto.brilltech.maaser.entities.SmsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.entities.SmsRequest.displayName = 'proto.brilltech.maaser.entities.SmsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.EmailRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.brilltech.maaser.entities.EmailRequest.repeatedFields_, null);
};
goog.inherits(proto.brilltech.maaser.entities.EmailRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.entities.EmailRequest.displayName = 'proto.brilltech.maaser.entities.EmailRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.Recipient = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.brilltech.maaser.entities.Recipient, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.entities.Recipient.displayName = 'proto.brilltech.maaser.entities.Recipient';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.PushNotificationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.brilltech.maaser.entities.PushNotificationRequest.repeatedFields_, null);
};
goog.inherits(proto.brilltech.maaser.entities.PushNotificationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.entities.PushNotificationRequest.displayName = 'proto.brilltech.maaser.entities.PushNotificationRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.NotificationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.brilltech.maaser.entities.NotificationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.entities.NotificationRequest.displayName = 'proto.brilltech.maaser.entities.NotificationRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.entities.Notification = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.brilltech.maaser.entities.Notification, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.entities.Notification.displayName = 'proto.brilltech.maaser.entities.Notification';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.brilltech.maaser.entities.SmsRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.SmsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.SmsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.SmsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.SmsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    tosList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    message: jspb.Message.getFieldWithDefault(msg, 2, ""),
    pin: jspb.Message.getFieldWithDefault(msg, 3, 0),
    ispin: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    senderuserid: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.SmsRequest}
 */
proto.brilltech.maaser.entities.SmsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.SmsRequest;
  return proto.brilltech.maaser.entities.SmsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.SmsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.SmsRequest}
 */
proto.brilltech.maaser.entities.SmsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addTos(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPin(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIspin(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSenderuserid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.SmsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.SmsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.SmsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.SmsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTosList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPin();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getIspin();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getSenderuserid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * repeated string tos = 1;
 * @return {!Array<string>}
 */
proto.brilltech.maaser.entities.SmsRequest.prototype.getTosList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.brilltech.maaser.entities.SmsRequest} returns this
 */
proto.brilltech.maaser.entities.SmsRequest.prototype.setTosList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.SmsRequest} returns this
 */
proto.brilltech.maaser.entities.SmsRequest.prototype.addTos = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.entities.SmsRequest} returns this
 */
proto.brilltech.maaser.entities.SmsRequest.prototype.clearTosList = function() {
  return this.setTosList([]);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.brilltech.maaser.entities.SmsRequest.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.SmsRequest} returns this
 */
proto.brilltech.maaser.entities.SmsRequest.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 pin = 3;
 * @return {number}
 */
proto.brilltech.maaser.entities.SmsRequest.prototype.getPin = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.entities.SmsRequest} returns this
 */
proto.brilltech.maaser.entities.SmsRequest.prototype.setPin = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional bool isPin = 4;
 * @return {boolean}
 */
proto.brilltech.maaser.entities.SmsRequest.prototype.getIspin = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.entities.SmsRequest} returns this
 */
proto.brilltech.maaser.entities.SmsRequest.prototype.setIspin = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional string senderUserId = 5;
 * @return {string}
 */
proto.brilltech.maaser.entities.SmsRequest.prototype.getSenderuserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.SmsRequest} returns this
 */
proto.brilltech.maaser.entities.SmsRequest.prototype.setSenderuserid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.brilltech.maaser.entities.EmailRequest.repeatedFields_ = [1,9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.EmailRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.EmailRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.EmailRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    tosList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    body: jspb.Message.getFieldWithDefault(msg, 2, ""),
    subject: jspb.Message.getFieldWithDefault(msg, 3, ""),
    from: jspb.Message.getFieldWithDefault(msg, 4, ""),
    template: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    html: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    templatename: jspb.Message.getFieldWithDefault(msg, 7, ""),
    templatedataMap: (f = msg.getTemplatedataMap()) ? f.toObject(includeInstance, undefined) : [],
    replytoaddressesList: (f = jspb.Message.getRepeatedField(msg, 9)) == null ? undefined : f,
    emailtype: jspb.Message.getFieldWithDefault(msg, 10, 0),
    senderuserid: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.EmailRequest}
 */
proto.brilltech.maaser.entities.EmailRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.EmailRequest;
  return proto.brilltech.maaser.entities.EmailRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.EmailRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.EmailRequest}
 */
proto.brilltech.maaser.entities.EmailRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addTos(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBody(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubject(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setFrom(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTemplate(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHtml(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTemplatename(value);
      break;
    case 8:
      var value = msg.getTemplatedataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.addReplytoaddresses(value);
      break;
    case 10:
      var value = /** @type {!proto.brilltech.maaser.entities.EmailType} */ (reader.readEnum());
      msg.setEmailtype(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setSenderuserid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.EmailRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.EmailRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.EmailRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTosList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getBody();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSubject();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFrom();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getTemplate();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getHtml();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getTemplatename();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getTemplatedataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(8, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getReplytoaddressesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      9,
      f
    );
  }
  f = message.getEmailtype();
  if (f !== 0.0) {
    writer.writeEnum(
      10,
      f
    );
  }
  f = message.getSenderuserid();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * repeated string tos = 1;
 * @return {!Array<string>}
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.getTosList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.brilltech.maaser.entities.EmailRequest} returns this
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.setTosList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.EmailRequest} returns this
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.addTos = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.entities.EmailRequest} returns this
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.clearTosList = function() {
  return this.setTosList([]);
};


/**
 * optional string body = 2;
 * @return {string}
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.getBody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.EmailRequest} returns this
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.setBody = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string subject = 3;
 * @return {string}
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.getSubject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.EmailRequest} returns this
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.setSubject = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string from = 4;
 * @return {string}
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.getFrom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.EmailRequest} returns this
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.setFrom = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional bool template = 5;
 * @return {boolean}
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.getTemplate = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.entities.EmailRequest} returns this
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.setTemplate = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool html = 6;
 * @return {boolean}
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.getHtml = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.entities.EmailRequest} returns this
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.setHtml = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional string templateName = 7;
 * @return {string}
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.getTemplatename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.EmailRequest} returns this
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.setTemplatename = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * map<string, string> templateData = 8;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.getTemplatedataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 8, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.brilltech.maaser.entities.EmailRequest} returns this
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.clearTemplatedataMap = function() {
  this.getTemplatedataMap().clear();
  return this;};


/**
 * repeated string replyToAddresses = 9;
 * @return {!Array<string>}
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.getReplytoaddressesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 9));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.brilltech.maaser.entities.EmailRequest} returns this
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.setReplytoaddressesList = function(value) {
  return jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.EmailRequest} returns this
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.addReplytoaddresses = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.entities.EmailRequest} returns this
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.clearReplytoaddressesList = function() {
  return this.setReplytoaddressesList([]);
};


/**
 * optional EmailType emailType = 10;
 * @return {!proto.brilltech.maaser.entities.EmailType}
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.getEmailtype = function() {
  return /** @type {!proto.brilltech.maaser.entities.EmailType} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {!proto.brilltech.maaser.entities.EmailType} value
 * @return {!proto.brilltech.maaser.entities.EmailRequest} returns this
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.setEmailtype = function(value) {
  return jspb.Message.setProto3EnumField(this, 10, value);
};


/**
 * optional string senderUserId = 11;
 * @return {string}
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.getSenderuserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.EmailRequest} returns this
 */
proto.brilltech.maaser.entities.EmailRequest.prototype.setSenderuserid = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.Recipient.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.Recipient.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.Recipient} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.Recipient.toObject = function(includeInstance, msg) {
  var f, obj = {
    to: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.Recipient}
 */
proto.brilltech.maaser.entities.Recipient.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.Recipient;
  return proto.brilltech.maaser.entities.Recipient.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.Recipient} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.Recipient}
 */
proto.brilltech.maaser.entities.Recipient.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTo(value);
      break;
    case 2:
      var value = /** @type {!proto.brilltech.maaser.entities.RecipientType} */ (reader.readEnum());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.Recipient.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.Recipient.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.Recipient} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.Recipient.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTo();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * optional string to = 1;
 * @return {string}
 */
proto.brilltech.maaser.entities.Recipient.prototype.getTo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Recipient} returns this
 */
proto.brilltech.maaser.entities.Recipient.prototype.setTo = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional RecipientType type = 2;
 * @return {!proto.brilltech.maaser.entities.RecipientType}
 */
proto.brilltech.maaser.entities.Recipient.prototype.getType = function() {
  return /** @type {!proto.brilltech.maaser.entities.RecipientType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.brilltech.maaser.entities.RecipientType} value
 * @return {!proto.brilltech.maaser.entities.Recipient} returns this
 */
proto.brilltech.maaser.entities.Recipient.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.brilltech.maaser.entities.PushNotificationRequest.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.PushNotificationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.PushNotificationRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.PushNotificationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    recipientsList: jspb.Message.toObjectList(msg.getRecipientsList(),
    proto.brilltech.maaser.entities.Recipient.toObject, includeInstance),
    excludedpushtokenList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    silent: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    persist: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    title: jspb.Message.getFieldWithDefault(msg, 5, ""),
    body: jspb.Message.getFieldWithDefault(msg, 6, ""),
    devicetype: jspb.Message.getFieldWithDefault(msg, 7, 0),
    fromuserid: jspb.Message.getFieldWithDefault(msg, 8, ""),
    notificationid: jspb.Message.getFieldWithDefault(msg, 9, ""),
    senderpushtoken: jspb.Message.getFieldWithDefault(msg, 10, ""),
    payload: jspb.Message.getFieldWithDefault(msg, 11, ""),
    notificationtype: jspb.Message.getFieldWithDefault(msg, 12, 0),
    timestamp: jspb.Message.getFieldWithDefault(msg, 13, 0),
    avatarimage: jspb.Message.getFieldWithDefault(msg, 14, ""),
    image: jspb.Message.getFieldWithDefault(msg, 15, ""),
    clickaction: jspb.Message.getFieldWithDefault(msg, 16, ""),
    dataMap: (f = msg.getDataMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.PushNotificationRequest;
  return proto.brilltech.maaser.entities.PushNotificationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.PushNotificationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.brilltech.maaser.entities.Recipient;
      reader.readMessage(value,proto.brilltech.maaser.entities.Recipient.deserializeBinaryFromReader);
      msg.addRecipients(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addExcludedpushtoken(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSilent(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPersist(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setBody(value);
      break;
    case 7:
      var value = /** @type {!proto.brilltech.maaser.entities.DeliveryDeviceType} */ (reader.readEnum());
      msg.setDevicetype(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setFromuserid(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotificationid(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setSenderpushtoken(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setPayload(value);
      break;
    case 12:
      var value = /** @type {!proto.brilltech.maaser.entities.NotificationType} */ (reader.readEnum());
      msg.setNotificationtype(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setAvatarimage(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setImage(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setClickaction(value);
      break;
    case 17:
      var value = msg.getDataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.PushNotificationRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.PushNotificationRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.PushNotificationRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRecipientsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.brilltech.maaser.entities.Recipient.serializeBinaryToWriter
    );
  }
  f = message.getExcludedpushtokenList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getSilent();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getPersist();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getBody();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getDevicetype();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getFromuserid();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getNotificationid();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getSenderpushtoken();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getPayload();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getNotificationtype();
  if (f !== 0.0) {
    writer.writeEnum(
      12,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      13,
      f
    );
  }
  f = message.getAvatarimage();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getImage();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getClickaction();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getDataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(17, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * repeated Recipient recipients = 1;
 * @return {!Array<!proto.brilltech.maaser.entities.Recipient>}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.getRecipientsList = function() {
  return /** @type{!Array<!proto.brilltech.maaser.entities.Recipient>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.brilltech.maaser.entities.Recipient, 1));
};


/**
 * @param {!Array<!proto.brilltech.maaser.entities.Recipient>} value
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
*/
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.setRecipientsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.brilltech.maaser.entities.Recipient=} opt_value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.Recipient}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.addRecipients = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.brilltech.maaser.entities.Recipient, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.clearRecipientsList = function() {
  return this.setRecipientsList([]);
};


/**
 * repeated string excludedPushToken = 2;
 * @return {!Array<string>}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.getExcludedpushtokenList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.setExcludedpushtokenList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.addExcludedpushtoken = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.clearExcludedpushtokenList = function() {
  return this.setExcludedpushtokenList([]);
};


/**
 * optional bool silent = 3;
 * @return {boolean}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.getSilent = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.setSilent = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool persist = 4;
 * @return {boolean}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.getPersist = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.setPersist = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional string title = 5;
 * @return {string}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string body = 6;
 * @return {string}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.getBody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.setBody = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional DeliveryDeviceType deviceType = 7;
 * @return {!proto.brilltech.maaser.entities.DeliveryDeviceType}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.getDevicetype = function() {
  return /** @type {!proto.brilltech.maaser.entities.DeliveryDeviceType} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.brilltech.maaser.entities.DeliveryDeviceType} value
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.setDevicetype = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional string fromUserId = 8;
 * @return {string}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.getFromuserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.setFromuserid = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string notificationId = 9;
 * @return {string}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.getNotificationid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.setNotificationid = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string senderPushToken = 10;
 * @return {string}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.getSenderpushtoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.setSenderpushtoken = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string payload = 11;
 * @return {string}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.getPayload = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.setPayload = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional NotificationType notificationType = 12;
 * @return {!proto.brilltech.maaser.entities.NotificationType}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.getNotificationtype = function() {
  return /** @type {!proto.brilltech.maaser.entities.NotificationType} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {!proto.brilltech.maaser.entities.NotificationType} value
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.setNotificationtype = function(value) {
  return jspb.Message.setProto3EnumField(this, 12, value);
};


/**
 * optional int64 timestamp = 13;
 * @return {number}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional string avatarImage = 14;
 * @return {string}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.getAvatarimage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.setAvatarimage = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional string image = 15;
 * @return {string}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.getImage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.setImage = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional string clickAction = 16;
 * @return {string}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.getClickaction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.setClickaction = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * map<string, string> data = 17;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.getDataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 17, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.brilltech.maaser.entities.PushNotificationRequest} returns this
 */
proto.brilltech.maaser.entities.PushNotificationRequest.prototype.clearDataMap = function() {
  this.getDataMap().clear();
  return this;};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.NotificationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.NotificationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.NotificationRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.NotificationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    smsrequest: (f = msg.getSmsrequest()) && proto.brilltech.maaser.entities.SmsRequest.toObject(includeInstance, f),
    emailrequest: (f = msg.getEmailrequest()) && proto.brilltech.maaser.entities.EmailRequest.toObject(includeInstance, f),
    pushnotificationrequest: (f = msg.getPushnotificationrequest()) && proto.brilltech.maaser.entities.PushNotificationRequest.toObject(includeInstance, f),
    notificationrequestmode: jspb.Message.getFieldWithDefault(msg, 4, 0),
    notificationrequestid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    timestamp: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.NotificationRequest}
 */
proto.brilltech.maaser.entities.NotificationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.NotificationRequest;
  return proto.brilltech.maaser.entities.NotificationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.NotificationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.NotificationRequest}
 */
proto.brilltech.maaser.entities.NotificationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.brilltech.maaser.entities.SmsRequest;
      reader.readMessage(value,proto.brilltech.maaser.entities.SmsRequest.deserializeBinaryFromReader);
      msg.setSmsrequest(value);
      break;
    case 2:
      var value = new proto.brilltech.maaser.entities.EmailRequest;
      reader.readMessage(value,proto.brilltech.maaser.entities.EmailRequest.deserializeBinaryFromReader);
      msg.setEmailrequest(value);
      break;
    case 3:
      var value = new proto.brilltech.maaser.entities.PushNotificationRequest;
      reader.readMessage(value,proto.brilltech.maaser.entities.PushNotificationRequest.deserializeBinaryFromReader);
      msg.setPushnotificationrequest(value);
      break;
    case 4:
      var value = /** @type {!proto.brilltech.maaser.entities.NotificationRequestMode} */ (reader.readEnum());
      msg.setNotificationrequestmode(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotificationrequestid(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.NotificationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.NotificationRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.NotificationRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.NotificationRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSmsrequest();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.brilltech.maaser.entities.SmsRequest.serializeBinaryToWriter
    );
  }
  f = message.getEmailrequest();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.brilltech.maaser.entities.EmailRequest.serializeBinaryToWriter
    );
  }
  f = message.getPushnotificationrequest();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.brilltech.maaser.entities.PushNotificationRequest.serializeBinaryToWriter
    );
  }
  f = message.getNotificationrequestmode();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getNotificationrequestid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
};


/**
 * optional SmsRequest smsRequest = 1;
 * @return {?proto.brilltech.maaser.entities.SmsRequest}
 */
proto.brilltech.maaser.entities.NotificationRequest.prototype.getSmsrequest = function() {
  return /** @type{?proto.brilltech.maaser.entities.SmsRequest} */ (
    jspb.Message.getWrapperField(this, proto.brilltech.maaser.entities.SmsRequest, 1));
};


/**
 * @param {?proto.brilltech.maaser.entities.SmsRequest|undefined} value
 * @return {!proto.brilltech.maaser.entities.NotificationRequest} returns this
*/
proto.brilltech.maaser.entities.NotificationRequest.prototype.setSmsrequest = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.entities.NotificationRequest} returns this
 */
proto.brilltech.maaser.entities.NotificationRequest.prototype.clearSmsrequest = function() {
  return this.setSmsrequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.entities.NotificationRequest.prototype.hasSmsrequest = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional EmailRequest emailRequest = 2;
 * @return {?proto.brilltech.maaser.entities.EmailRequest}
 */
proto.brilltech.maaser.entities.NotificationRequest.prototype.getEmailrequest = function() {
  return /** @type{?proto.brilltech.maaser.entities.EmailRequest} */ (
    jspb.Message.getWrapperField(this, proto.brilltech.maaser.entities.EmailRequest, 2));
};


/**
 * @param {?proto.brilltech.maaser.entities.EmailRequest|undefined} value
 * @return {!proto.brilltech.maaser.entities.NotificationRequest} returns this
*/
proto.brilltech.maaser.entities.NotificationRequest.prototype.setEmailrequest = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.entities.NotificationRequest} returns this
 */
proto.brilltech.maaser.entities.NotificationRequest.prototype.clearEmailrequest = function() {
  return this.setEmailrequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.entities.NotificationRequest.prototype.hasEmailrequest = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional PushNotificationRequest pushNotificationRequest = 3;
 * @return {?proto.brilltech.maaser.entities.PushNotificationRequest}
 */
proto.brilltech.maaser.entities.NotificationRequest.prototype.getPushnotificationrequest = function() {
  return /** @type{?proto.brilltech.maaser.entities.PushNotificationRequest} */ (
    jspb.Message.getWrapperField(this, proto.brilltech.maaser.entities.PushNotificationRequest, 3));
};


/**
 * @param {?proto.brilltech.maaser.entities.PushNotificationRequest|undefined} value
 * @return {!proto.brilltech.maaser.entities.NotificationRequest} returns this
*/
proto.brilltech.maaser.entities.NotificationRequest.prototype.setPushnotificationrequest = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.entities.NotificationRequest} returns this
 */
proto.brilltech.maaser.entities.NotificationRequest.prototype.clearPushnotificationrequest = function() {
  return this.setPushnotificationrequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.entities.NotificationRequest.prototype.hasPushnotificationrequest = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional NotificationRequestMode notificationRequestMode = 4;
 * @return {!proto.brilltech.maaser.entities.NotificationRequestMode}
 */
proto.brilltech.maaser.entities.NotificationRequest.prototype.getNotificationrequestmode = function() {
  return /** @type {!proto.brilltech.maaser.entities.NotificationRequestMode} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.brilltech.maaser.entities.NotificationRequestMode} value
 * @return {!proto.brilltech.maaser.entities.NotificationRequest} returns this
 */
proto.brilltech.maaser.entities.NotificationRequest.prototype.setNotificationrequestmode = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional string notificationRequestId = 5;
 * @return {string}
 */
proto.brilltech.maaser.entities.NotificationRequest.prototype.getNotificationrequestid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.NotificationRequest} returns this
 */
proto.brilltech.maaser.entities.NotificationRequest.prototype.setNotificationrequestid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int64 timestamp = 6;
 * @return {number}
 */
proto.brilltech.maaser.entities.NotificationRequest.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.entities.NotificationRequest} returns this
 */
proto.brilltech.maaser.entities.NotificationRequest.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.entities.Notification.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.entities.Notification.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.entities.Notification} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.Notification.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    notificationid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    title: jspb.Message.getFieldWithDefault(msg, 3, ""),
    body: jspb.Message.getFieldWithDefault(msg, 4, ""),
    senderid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    timestamp: jspb.Message.getFieldWithDefault(msg, 6, 0),
    payload: jspb.Message.getFieldWithDefault(msg, 7, ""),
    silent: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    avatarimage: jspb.Message.getFieldWithDefault(msg, 9, ""),
    image: jspb.Message.getFieldWithDefault(msg, 10, ""),
    clickaction: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.entities.Notification}
 */
proto.brilltech.maaser.entities.Notification.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.entities.Notification;
  return proto.brilltech.maaser.entities.Notification.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.entities.Notification} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.entities.Notification}
 */
proto.brilltech.maaser.entities.Notification.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.brilltech.maaser.entities.NotificationType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotificationid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBody(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSenderid(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setPayload(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSilent(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setAvatarimage(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setImage(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setClickaction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.entities.Notification.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.entities.Notification.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.entities.Notification} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.entities.Notification.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getNotificationid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBody();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getSenderid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getPayload();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getSilent();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getAvatarimage();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getImage();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getClickaction();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional NotificationType type = 1;
 * @return {!proto.brilltech.maaser.entities.NotificationType}
 */
proto.brilltech.maaser.entities.Notification.prototype.getType = function() {
  return /** @type {!proto.brilltech.maaser.entities.NotificationType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.brilltech.maaser.entities.NotificationType} value
 * @return {!proto.brilltech.maaser.entities.Notification} returns this
 */
proto.brilltech.maaser.entities.Notification.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string notificationId = 2;
 * @return {string}
 */
proto.brilltech.maaser.entities.Notification.prototype.getNotificationid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Notification} returns this
 */
proto.brilltech.maaser.entities.Notification.prototype.setNotificationid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string title = 3;
 * @return {string}
 */
proto.brilltech.maaser.entities.Notification.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Notification} returns this
 */
proto.brilltech.maaser.entities.Notification.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string body = 4;
 * @return {string}
 */
proto.brilltech.maaser.entities.Notification.prototype.getBody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Notification} returns this
 */
proto.brilltech.maaser.entities.Notification.prototype.setBody = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string senderId = 5;
 * @return {string}
 */
proto.brilltech.maaser.entities.Notification.prototype.getSenderid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Notification} returns this
 */
proto.brilltech.maaser.entities.Notification.prototype.setSenderid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int64 timestamp = 6;
 * @return {number}
 */
proto.brilltech.maaser.entities.Notification.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.entities.Notification} returns this
 */
proto.brilltech.maaser.entities.Notification.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string payload = 7;
 * @return {string}
 */
proto.brilltech.maaser.entities.Notification.prototype.getPayload = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Notification} returns this
 */
proto.brilltech.maaser.entities.Notification.prototype.setPayload = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional bool silent = 8;
 * @return {boolean}
 */
proto.brilltech.maaser.entities.Notification.prototype.getSilent = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.entities.Notification} returns this
 */
proto.brilltech.maaser.entities.Notification.prototype.setSilent = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional string avatarImage = 9;
 * @return {string}
 */
proto.brilltech.maaser.entities.Notification.prototype.getAvatarimage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Notification} returns this
 */
proto.brilltech.maaser.entities.Notification.prototype.setAvatarimage = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string image = 10;
 * @return {string}
 */
proto.brilltech.maaser.entities.Notification.prototype.getImage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Notification} returns this
 */
proto.brilltech.maaser.entities.Notification.prototype.setImage = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string clickAction = 11;
 * @return {string}
 */
proto.brilltech.maaser.entities.Notification.prototype.getClickaction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.entities.Notification} returns this
 */
proto.brilltech.maaser.entities.Notification.prototype.setClickaction = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * @enum {number}
 */
proto.brilltech.maaser.entities.EmailType = {
  UNKNOWN_EMAIL_TEMPLATE: 0,
  WELCOME_EMAIL: 1,
  EMAIL_VERIFICATION: 2,
  FORGOT_PASSWORD: 3,
  RESET_PASSWORD_CONFIRMATION: 4,
  PHONE_VERIFICATION: 5
};

/**
 * @enum {number}
 */
proto.brilltech.maaser.entities.RecipientType = {
  UNKNOWN_RECIPIENT: 0,
  USER_ID: 1,
  PUSH_TOKEN: 2,
  TOPIC: 3
};

/**
 * @enum {number}
 */
proto.brilltech.maaser.entities.NotificationType = {
  UNKNOWN_NOTIFICATION_TYPE: 0,
  TRANSACTION_NOTIFICATION: 1,
  CHARITY_EVENT_NOTIFICATION: 2
};

/**
 * @enum {number}
 */
proto.brilltech.maaser.entities.DeliveryDeviceType = {
  ALL: 0,
  ANDROID_ONLY: 1,
  IOS_ONLY: 2
};

/**
 * @enum {number}
 */
proto.brilltech.maaser.entities.NotificationRequestMode = {
  UNKNOWN_NOTIFICATION_MODE: 0,
  SEND_SMS: 1,
  SEND_EMAIL: 2,
  SEND_PUSH: 3,
  SEND_SMS_EMAIL: 4,
  SEND_SMS_PUSH: 5,
  SEND_EMAIL_PUSH: 6,
  SEND_TO_ALL: 7
};

goog.object.extend(exports, proto.brilltech.maaser.entities);
