// source: payment_rpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var treeleaf_pb = require('./treeleaf_pb.js');
goog.object.extend(proto, treeleaf_pb);
var payment_pb = require('./payment_pb.js');
goog.object.extend(proto, payment_pb);
var auth_pb = require('./auth_pb.js');
goog.object.extend(proto, auth_pb);
goog.exportSymbol('proto.brilltech.maaser.rpc.PaymentBaseRequest', null, global);
goog.exportSymbol('proto.brilltech.maaser.rpc.PaymentBaseResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.brilltech.maaser.rpc.PaymentBaseRequest.repeatedFields_, null);
};
goog.inherits(proto.brilltech.maaser.rpc.PaymentBaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.rpc.PaymentBaseRequest.displayName = 'proto.brilltech.maaser.rpc.PaymentBaseRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.brilltech.maaser.rpc.PaymentBaseResponse.repeatedFields_, null);
};
goog.inherits(proto.brilltech.maaser.rpc.PaymentBaseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.brilltech.maaser.rpc.PaymentBaseResponse.displayName = 'proto.brilltech.maaser.rpc.PaymentBaseResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.rpc.PaymentBaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.rpc.PaymentBaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    refid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    stringvalue: jspb.Message.getFieldWithDefault(msg, 2, ""),
    stringvaluesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    intvalue: jspb.Message.getFieldWithDefault(msg, 4, 0),
    longvalue: jspb.Message.getFieldWithDefault(msg, 5, 0),
    boolvalue: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    doublevalue: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    debug: (f = msg.getDebug()) && treeleaf_pb.Debug.toObject(includeInstance, f),
    authorization: (f = msg.getAuthorization()) && auth_pb.Authorization.toObject(includeInstance, f),
    card: (f = msg.getCard()) && payment_pb.Card.toObject(includeInstance, f),
    bank: (f = msg.getBank()) && payment_pb.Bank.toObject(includeInstance, f),
    transaction: (f = msg.getTransaction()) && payment_pb.Transaction.toObject(includeInstance, f),
    balance: (f = msg.getBalance()) && payment_pb.Transaction.toObject(includeInstance, f),
    dataquery: (f = msg.getDataquery()) && treeleaf_pb.DataQuery.toObject(includeInstance, f),
    scheduletransaction: (f = msg.getScheduletransaction()) && payment_pb.ScheduleTransaction.toObject(includeInstance, f),
    transactionfilter: (f = msg.getTransactionfilter()) && payment_pb.TransactionFilter.toObject(includeInstance, f),
    transactionexportrequest: (f = msg.getTransactionexportrequest()) && payment_pb.TransactionExportRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.rpc.PaymentBaseRequest;
  return proto.brilltech.maaser.rpc.PaymentBaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.rpc.PaymentBaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRefid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringvalue(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addStringvalues(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIntvalue(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLongvalue(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBoolvalue(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDoublevalue(value);
      break;
    case 8:
      var value = new treeleaf_pb.Debug;
      reader.readMessage(value,treeleaf_pb.Debug.deserializeBinaryFromReader);
      msg.setDebug(value);
      break;
    case 9:
      var value = new auth_pb.Authorization;
      reader.readMessage(value,auth_pb.Authorization.deserializeBinaryFromReader);
      msg.setAuthorization(value);
      break;
    case 10:
      var value = new payment_pb.Card;
      reader.readMessage(value,payment_pb.Card.deserializeBinaryFromReader);
      msg.setCard(value);
      break;
    case 11:
      var value = new payment_pb.Bank;
      reader.readMessage(value,payment_pb.Bank.deserializeBinaryFromReader);
      msg.setBank(value);
      break;
    case 12:
      var value = new payment_pb.Transaction;
      reader.readMessage(value,payment_pb.Transaction.deserializeBinaryFromReader);
      msg.setTransaction(value);
      break;
    case 13:
      var value = new payment_pb.Transaction;
      reader.readMessage(value,payment_pb.Transaction.deserializeBinaryFromReader);
      msg.setBalance(value);
      break;
    case 14:
      var value = new treeleaf_pb.DataQuery;
      reader.readMessage(value,treeleaf_pb.DataQuery.deserializeBinaryFromReader);
      msg.setDataquery(value);
      break;
    case 15:
      var value = new payment_pb.ScheduleTransaction;
      reader.readMessage(value,payment_pb.ScheduleTransaction.deserializeBinaryFromReader);
      msg.setScheduletransaction(value);
      break;
    case 16:
      var value = new payment_pb.TransactionFilter;
      reader.readMessage(value,payment_pb.TransactionFilter.deserializeBinaryFromReader);
      msg.setTransactionfilter(value);
      break;
    case 17:
      var value = new payment_pb.TransactionExportRequest;
      reader.readMessage(value,payment_pb.TransactionExportRequest.deserializeBinaryFromReader);
      msg.setTransactionexportrequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.rpc.PaymentBaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.rpc.PaymentBaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRefid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStringvalue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStringvaluesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getIntvalue();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getLongvalue();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getBoolvalue();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getDoublevalue();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getDebug();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      treeleaf_pb.Debug.serializeBinaryToWriter
    );
  }
  f = message.getAuthorization();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      auth_pb.Authorization.serializeBinaryToWriter
    );
  }
  f = message.getCard();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      payment_pb.Card.serializeBinaryToWriter
    );
  }
  f = message.getBank();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      payment_pb.Bank.serializeBinaryToWriter
    );
  }
  f = message.getTransaction();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      payment_pb.Transaction.serializeBinaryToWriter
    );
  }
  f = message.getBalance();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      payment_pb.Transaction.serializeBinaryToWriter
    );
  }
  f = message.getDataquery();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      treeleaf_pb.DataQuery.serializeBinaryToWriter
    );
  }
  f = message.getScheduletransaction();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      payment_pb.ScheduleTransaction.serializeBinaryToWriter
    );
  }
  f = message.getTransactionfilter();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      payment_pb.TransactionFilter.serializeBinaryToWriter
    );
  }
  f = message.getTransactionexportrequest();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      payment_pb.TransactionExportRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional string refId = 1;
 * @return {string}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.getRefid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.setRefid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string stringValue = 2;
 * @return {string}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.getStringvalue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.setStringvalue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string stringValues = 3;
 * @return {!Array<string>}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.getStringvaluesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.setStringvaluesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.addStringvalues = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.clearStringvaluesList = function() {
  return this.setStringvaluesList([]);
};


/**
 * optional int32 intValue = 4;
 * @return {number}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.getIntvalue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.setIntvalue = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 longValue = 5;
 * @return {number}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.getLongvalue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.setLongvalue = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional bool boolValue = 6;
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.getBoolvalue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.setBoolvalue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool doubleValue = 7;
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.getDoublevalue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.setDoublevalue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional treeleaf.protos.Debug debug = 8;
 * @return {?proto.treeleaf.protos.Debug}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.getDebug = function() {
  return /** @type{?proto.treeleaf.protos.Debug} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.Debug, 8));
};


/**
 * @param {?proto.treeleaf.protos.Debug|undefined} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.setDebug = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.clearDebug = function() {
  return this.setDebug(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.hasDebug = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional brilltech.maaser.entities.Authorization authorization = 9;
 * @return {?proto.brilltech.maaser.entities.Authorization}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.getAuthorization = function() {
  return /** @type{?proto.brilltech.maaser.entities.Authorization} */ (
    jspb.Message.getWrapperField(this, auth_pb.Authorization, 9));
};


/**
 * @param {?proto.brilltech.maaser.entities.Authorization|undefined} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.setAuthorization = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.clearAuthorization = function() {
  return this.setAuthorization(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.hasAuthorization = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional brilltech.maaser.entities.Card card = 10;
 * @return {?proto.brilltech.maaser.entities.Card}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.getCard = function() {
  return /** @type{?proto.brilltech.maaser.entities.Card} */ (
    jspb.Message.getWrapperField(this, payment_pb.Card, 10));
};


/**
 * @param {?proto.brilltech.maaser.entities.Card|undefined} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.setCard = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.clearCard = function() {
  return this.setCard(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.hasCard = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional brilltech.maaser.entities.Bank bank = 11;
 * @return {?proto.brilltech.maaser.entities.Bank}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.getBank = function() {
  return /** @type{?proto.brilltech.maaser.entities.Bank} */ (
    jspb.Message.getWrapperField(this, payment_pb.Bank, 11));
};


/**
 * @param {?proto.brilltech.maaser.entities.Bank|undefined} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.setBank = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.clearBank = function() {
  return this.setBank(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.hasBank = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional brilltech.maaser.entities.Transaction transaction = 12;
 * @return {?proto.brilltech.maaser.entities.Transaction}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.getTransaction = function() {
  return /** @type{?proto.brilltech.maaser.entities.Transaction} */ (
    jspb.Message.getWrapperField(this, payment_pb.Transaction, 12));
};


/**
 * @param {?proto.brilltech.maaser.entities.Transaction|undefined} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.setTransaction = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.clearTransaction = function() {
  return this.setTransaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.hasTransaction = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional brilltech.maaser.entities.Transaction balance = 13;
 * @return {?proto.brilltech.maaser.entities.Transaction}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.getBalance = function() {
  return /** @type{?proto.brilltech.maaser.entities.Transaction} */ (
    jspb.Message.getWrapperField(this, payment_pb.Transaction, 13));
};


/**
 * @param {?proto.brilltech.maaser.entities.Transaction|undefined} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.setBalance = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.clearBalance = function() {
  return this.setBalance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.hasBalance = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional treeleaf.protos.DataQuery dataQuery = 14;
 * @return {?proto.treeleaf.protos.DataQuery}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.getDataquery = function() {
  return /** @type{?proto.treeleaf.protos.DataQuery} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.DataQuery, 14));
};


/**
 * @param {?proto.treeleaf.protos.DataQuery|undefined} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.setDataquery = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.clearDataquery = function() {
  return this.setDataquery(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.hasDataquery = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional brilltech.maaser.entities.ScheduleTransaction scheduleTransaction = 15;
 * @return {?proto.brilltech.maaser.entities.ScheduleTransaction}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.getScheduletransaction = function() {
  return /** @type{?proto.brilltech.maaser.entities.ScheduleTransaction} */ (
    jspb.Message.getWrapperField(this, payment_pb.ScheduleTransaction, 15));
};


/**
 * @param {?proto.brilltech.maaser.entities.ScheduleTransaction|undefined} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.setScheduletransaction = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.clearScheduletransaction = function() {
  return this.setScheduletransaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.hasScheduletransaction = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional brilltech.maaser.entities.TransactionFilter transactionFilter = 16;
 * @return {?proto.brilltech.maaser.entities.TransactionFilter}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.getTransactionfilter = function() {
  return /** @type{?proto.brilltech.maaser.entities.TransactionFilter} */ (
    jspb.Message.getWrapperField(this, payment_pb.TransactionFilter, 16));
};


/**
 * @param {?proto.brilltech.maaser.entities.TransactionFilter|undefined} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.setTransactionfilter = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.clearTransactionfilter = function() {
  return this.setTransactionfilter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.hasTransactionfilter = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional brilltech.maaser.entities.TransactionExportRequest transactionExportRequest = 17;
 * @return {?proto.brilltech.maaser.entities.TransactionExportRequest}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.getTransactionexportrequest = function() {
  return /** @type{?proto.brilltech.maaser.entities.TransactionExportRequest} */ (
    jspb.Message.getWrapperField(this, payment_pb.TransactionExportRequest, 17));
};


/**
 * @param {?proto.brilltech.maaser.entities.TransactionExportRequest|undefined} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.setTransactionexportrequest = function(value) {
  return jspb.Message.setWrapperField(this, 17, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseRequest} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.clearTransactionexportrequest = function() {
  return this.setTransactionexportrequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseRequest.prototype.hasTransactionexportrequest = function() {
  return jspb.Message.getField(this, 17) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.repeatedFields_ = [8,10,12,15,16];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.brilltech.maaser.rpc.PaymentBaseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.brilltech.maaser.rpc.PaymentBaseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    error: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    msg: jspb.Message.getFieldWithDefault(msg, 2, ""),
    errorcode: jspb.Message.getFieldWithDefault(msg, 3, 0),
    success: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    timestamp: jspb.Message.getFieldWithDefault(msg, 5, 0),
    debug: (f = msg.getDebug()) && treeleaf_pb.Debug.toObject(includeInstance, f),
    card: (f = msg.getCard()) && payment_pb.Card.toObject(includeInstance, f),
    cardsList: jspb.Message.toObjectList(msg.getCardsList(),
    payment_pb.Card.toObject, includeInstance),
    bank: (f = msg.getBank()) && payment_pb.Bank.toObject(includeInstance, f),
    banksList: jspb.Message.toObjectList(msg.getBanksList(),
    payment_pb.Bank.toObject, includeInstance),
    transaction: (f = msg.getTransaction()) && payment_pb.Transaction.toObject(includeInstance, f),
    transactionsList: jspb.Message.toObjectList(msg.getTransactionsList(),
    payment_pb.Transaction.toObject, includeInstance),
    balance: (f = msg.getBalance()) && payment_pb.Balance.toObject(includeInstance, f),
    scheduletransaction: (f = msg.getScheduletransaction()) && payment_pb.ScheduleTransaction.toObject(includeInstance, f),
    scheduletransactionsList: jspb.Message.toObjectList(msg.getScheduletransactionsList(),
    payment_pb.ScheduleTransaction.toObject, includeInstance),
    donationsList: jspb.Message.toObjectList(msg.getDonationsList(),
    payment_pb.CampaignDonation.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.brilltech.maaser.rpc.PaymentBaseResponse;
  return proto.brilltech.maaser.rpc.PaymentBaseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.brilltech.maaser.rpc.PaymentBaseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setError(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsg(value);
      break;
    case 3:
      var value = /** @type {!proto.treeleaf.protos.ErrorCode} */ (reader.readEnum());
      msg.setErrorcode(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 6:
      var value = new treeleaf_pb.Debug;
      reader.readMessage(value,treeleaf_pb.Debug.deserializeBinaryFromReader);
      msg.setDebug(value);
      break;
    case 7:
      var value = new payment_pb.Card;
      reader.readMessage(value,payment_pb.Card.deserializeBinaryFromReader);
      msg.setCard(value);
      break;
    case 8:
      var value = new payment_pb.Card;
      reader.readMessage(value,payment_pb.Card.deserializeBinaryFromReader);
      msg.addCards(value);
      break;
    case 9:
      var value = new payment_pb.Bank;
      reader.readMessage(value,payment_pb.Bank.deserializeBinaryFromReader);
      msg.setBank(value);
      break;
    case 10:
      var value = new payment_pb.Bank;
      reader.readMessage(value,payment_pb.Bank.deserializeBinaryFromReader);
      msg.addBanks(value);
      break;
    case 11:
      var value = new payment_pb.Transaction;
      reader.readMessage(value,payment_pb.Transaction.deserializeBinaryFromReader);
      msg.setTransaction(value);
      break;
    case 12:
      var value = new payment_pb.Transaction;
      reader.readMessage(value,payment_pb.Transaction.deserializeBinaryFromReader);
      msg.addTransactions(value);
      break;
    case 13:
      var value = new payment_pb.Balance;
      reader.readMessage(value,payment_pb.Balance.deserializeBinaryFromReader);
      msg.setBalance(value);
      break;
    case 14:
      var value = new payment_pb.ScheduleTransaction;
      reader.readMessage(value,payment_pb.ScheduleTransaction.deserializeBinaryFromReader);
      msg.setScheduletransaction(value);
      break;
    case 15:
      var value = new payment_pb.ScheduleTransaction;
      reader.readMessage(value,payment_pb.ScheduleTransaction.deserializeBinaryFromReader);
      msg.addScheduletransactions(value);
      break;
    case 16:
      var value = new payment_pb.CampaignDonation;
      reader.readMessage(value,payment_pb.CampaignDonation.deserializeBinaryFromReader);
      msg.addDonations(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.brilltech.maaser.rpc.PaymentBaseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.brilltech.maaser.rpc.PaymentBaseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getError();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getMsg();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getErrorcode();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getDebug();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      treeleaf_pb.Debug.serializeBinaryToWriter
    );
  }
  f = message.getCard();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      payment_pb.Card.serializeBinaryToWriter
    );
  }
  f = message.getCardsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      payment_pb.Card.serializeBinaryToWriter
    );
  }
  f = message.getBank();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      payment_pb.Bank.serializeBinaryToWriter
    );
  }
  f = message.getBanksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      payment_pb.Bank.serializeBinaryToWriter
    );
  }
  f = message.getTransaction();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      payment_pb.Transaction.serializeBinaryToWriter
    );
  }
  f = message.getTransactionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      payment_pb.Transaction.serializeBinaryToWriter
    );
  }
  f = message.getBalance();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      payment_pb.Balance.serializeBinaryToWriter
    );
  }
  f = message.getScheduletransaction();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      payment_pb.ScheduleTransaction.serializeBinaryToWriter
    );
  }
  f = message.getScheduletransactionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      15,
      f,
      payment_pb.ScheduleTransaction.serializeBinaryToWriter
    );
  }
  f = message.getDonationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      16,
      f,
      payment_pb.CampaignDonation.serializeBinaryToWriter
    );
  }
};


/**
 * optional bool error = 1;
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.getError = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.setError = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string msg = 2;
 * @return {string}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.getMsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.setMsg = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional treeleaf.protos.ErrorCode errorCode = 3;
 * @return {!proto.treeleaf.protos.ErrorCode}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.getErrorcode = function() {
  return /** @type {!proto.treeleaf.protos.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.treeleaf.protos.ErrorCode} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.setErrorcode = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional bool success = 4;
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional int64 timestamp = 5;
 * @return {number}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional treeleaf.protos.Debug debug = 6;
 * @return {?proto.treeleaf.protos.Debug}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.getDebug = function() {
  return /** @type{?proto.treeleaf.protos.Debug} */ (
    jspb.Message.getWrapperField(this, treeleaf_pb.Debug, 6));
};


/**
 * @param {?proto.treeleaf.protos.Debug|undefined} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.setDebug = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.clearDebug = function() {
  return this.setDebug(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.hasDebug = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional brilltech.maaser.entities.Card card = 7;
 * @return {?proto.brilltech.maaser.entities.Card}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.getCard = function() {
  return /** @type{?proto.brilltech.maaser.entities.Card} */ (
    jspb.Message.getWrapperField(this, payment_pb.Card, 7));
};


/**
 * @param {?proto.brilltech.maaser.entities.Card|undefined} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.setCard = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.clearCard = function() {
  return this.setCard(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.hasCard = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * repeated brilltech.maaser.entities.Card cards = 8;
 * @return {!Array<!proto.brilltech.maaser.entities.Card>}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.getCardsList = function() {
  return /** @type{!Array<!proto.brilltech.maaser.entities.Card>} */ (
    jspb.Message.getRepeatedWrapperField(this, payment_pb.Card, 8));
};


/**
 * @param {!Array<!proto.brilltech.maaser.entities.Card>} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.setCardsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.brilltech.maaser.entities.Card=} opt_value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.Card}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.addCards = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.brilltech.maaser.entities.Card, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.clearCardsList = function() {
  return this.setCardsList([]);
};


/**
 * optional brilltech.maaser.entities.Bank bank = 9;
 * @return {?proto.brilltech.maaser.entities.Bank}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.getBank = function() {
  return /** @type{?proto.brilltech.maaser.entities.Bank} */ (
    jspb.Message.getWrapperField(this, payment_pb.Bank, 9));
};


/**
 * @param {?proto.brilltech.maaser.entities.Bank|undefined} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.setBank = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.clearBank = function() {
  return this.setBank(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.hasBank = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * repeated brilltech.maaser.entities.Bank banks = 10;
 * @return {!Array<!proto.brilltech.maaser.entities.Bank>}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.getBanksList = function() {
  return /** @type{!Array<!proto.brilltech.maaser.entities.Bank>} */ (
    jspb.Message.getRepeatedWrapperField(this, payment_pb.Bank, 10));
};


/**
 * @param {!Array<!proto.brilltech.maaser.entities.Bank>} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.setBanksList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.brilltech.maaser.entities.Bank=} opt_value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.Bank}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.addBanks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.brilltech.maaser.entities.Bank, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.clearBanksList = function() {
  return this.setBanksList([]);
};


/**
 * optional brilltech.maaser.entities.Transaction transaction = 11;
 * @return {?proto.brilltech.maaser.entities.Transaction}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.getTransaction = function() {
  return /** @type{?proto.brilltech.maaser.entities.Transaction} */ (
    jspb.Message.getWrapperField(this, payment_pb.Transaction, 11));
};


/**
 * @param {?proto.brilltech.maaser.entities.Transaction|undefined} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.setTransaction = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.clearTransaction = function() {
  return this.setTransaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.hasTransaction = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * repeated brilltech.maaser.entities.Transaction transactions = 12;
 * @return {!Array<!proto.brilltech.maaser.entities.Transaction>}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.getTransactionsList = function() {
  return /** @type{!Array<!proto.brilltech.maaser.entities.Transaction>} */ (
    jspb.Message.getRepeatedWrapperField(this, payment_pb.Transaction, 12));
};


/**
 * @param {!Array<!proto.brilltech.maaser.entities.Transaction>} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.setTransactionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.brilltech.maaser.entities.Transaction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.Transaction}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.addTransactions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.brilltech.maaser.entities.Transaction, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.clearTransactionsList = function() {
  return this.setTransactionsList([]);
};


/**
 * optional brilltech.maaser.entities.Balance balance = 13;
 * @return {?proto.brilltech.maaser.entities.Balance}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.getBalance = function() {
  return /** @type{?proto.brilltech.maaser.entities.Balance} */ (
    jspb.Message.getWrapperField(this, payment_pb.Balance, 13));
};


/**
 * @param {?proto.brilltech.maaser.entities.Balance|undefined} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.setBalance = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.clearBalance = function() {
  return this.setBalance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.hasBalance = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional brilltech.maaser.entities.ScheduleTransaction scheduleTransaction = 14;
 * @return {?proto.brilltech.maaser.entities.ScheduleTransaction}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.getScheduletransaction = function() {
  return /** @type{?proto.brilltech.maaser.entities.ScheduleTransaction} */ (
    jspb.Message.getWrapperField(this, payment_pb.ScheduleTransaction, 14));
};


/**
 * @param {?proto.brilltech.maaser.entities.ScheduleTransaction|undefined} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.setScheduletransaction = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.clearScheduletransaction = function() {
  return this.setScheduletransaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.hasScheduletransaction = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * repeated brilltech.maaser.entities.ScheduleTransaction scheduleTransactions = 15;
 * @return {!Array<!proto.brilltech.maaser.entities.ScheduleTransaction>}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.getScheduletransactionsList = function() {
  return /** @type{!Array<!proto.brilltech.maaser.entities.ScheduleTransaction>} */ (
    jspb.Message.getRepeatedWrapperField(this, payment_pb.ScheduleTransaction, 15));
};


/**
 * @param {!Array<!proto.brilltech.maaser.entities.ScheduleTransaction>} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.setScheduletransactionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 15, value);
};


/**
 * @param {!proto.brilltech.maaser.entities.ScheduleTransaction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.ScheduleTransaction}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.addScheduletransactions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 15, opt_value, proto.brilltech.maaser.entities.ScheduleTransaction, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.clearScheduletransactionsList = function() {
  return this.setScheduletransactionsList([]);
};


/**
 * repeated brilltech.maaser.entities.CampaignDonation donations = 16;
 * @return {!Array<!proto.brilltech.maaser.entities.CampaignDonation>}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.getDonationsList = function() {
  return /** @type{!Array<!proto.brilltech.maaser.entities.CampaignDonation>} */ (
    jspb.Message.getRepeatedWrapperField(this, payment_pb.CampaignDonation, 16));
};


/**
 * @param {!Array<!proto.brilltech.maaser.entities.CampaignDonation>} value
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
*/
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.setDonationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 16, value);
};


/**
 * @param {!proto.brilltech.maaser.entities.CampaignDonation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.brilltech.maaser.entities.CampaignDonation}
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.addDonations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 16, opt_value, proto.brilltech.maaser.entities.CampaignDonation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.brilltech.maaser.rpc.PaymentBaseResponse} returns this
 */
proto.brilltech.maaser.rpc.PaymentBaseResponse.prototype.clearDonationsList = function() {
  return this.setDonationsList([]);
};


goog.object.extend(exports, proto.brilltech.maaser.rpc);
